In [4]:
print("Hello World")

Hello World

## Data Loading and Preprocessing

In [5]:

from sentence_splitter import sentence_splitter
import pandas as pd

ss = sentence_splitter()
df = pd.read_csv(r"datasets\annotations_raw.csv")

In [6]:
import pandas as pd

labeled_df = df[["doc_name","label", "text"]].dropna().reset_index(drop=True)

# Step 1: Combine texts within each (doc_name, label)
grouped = (
    df.groupby(["doc_name", "label"])["text"]
      .apply(lambda x: " ".join(x.astype(str)))
      .reset_index()
)

# Step 2: Build full dictionary
case_dict = {}

for doc_name, sub_df in grouped.groupby("doc_name"):
    # Create label:text mapping for this case
    label_map = dict(zip(sub_df["label"], sub_df["text"]))
    # Assign to master dictionary
    case_dict[doc_name] = label_map

# --- Preview one case ---
first_key = list(case_dict.keys())[0]
print(first_key, "→", case_dict[first_key])

ECLI:NL:GHAMS:2015:2960.txt → {'beoordeling': 'Deze grief slaagt. Het staat vast dat [appellante] een doos met voedingssupplementen heeft achtergelaten bij [geïntimeerde] en dat [geïntimeerde] deze op dat moment heeft behouden en in elk geval een aantal van deze voedingssupplementen heeft gebruikt. De lezing van [appellante] dat de waarde van de doos met voedingssupplementen - naar in hoger beroep niet meer in geschil is: € 2.000,- - zou mogen worden afgetrokken van het geleende bedrag van € 15.000,- vindt bovendien steun in de eerdergenoemde brief van [appellante] , die ook door [geïntimeerde] is ondertekend. In het licht van dit een en ander acht het hof de bestrijding door [geïntimeerde] van de lezing van [appellante] onvoldoende gemotiveerd. Het beroep op verrekening slaagt daarom, zodat de terugbetalingsverplichting van [appellante] nog een bedrag van € 13.000,- beloopt. Van [appellante] had verwacht mogen worden dat zij ook inzicht zou geven in haar vermogenspositie Iedere verdere bijzonderheid te dien aanzien – bijvoorbeeld de waarde van die woning, eventuele hypothecaire schuld, eventuele financieringsmogelijkheden in verband met een en ander – is echter achterwege gebleven. Bij gebreke van toereikende gegevens aan de zijde van [appellante] bestaat onvoldoende aanknopingspunt om tot een andere betalingswijze van het resterende bedrag van € 13.000,- te besluiten, zodat grief 1 faalt. 3.9.\\nDeze grief faalt. Terugbetaling van het geleende bedrag was de inzet van het geding in eerste aanleg in conventie. Het verweer daartegen van [appellante] is verworpen. De omstandigheid dat de uitkomst is dat niet € 15.000,- maar € 13.000,- dient te worden terugbetaald en dat terugbetaling mogelijk is in een aantal termijnen, neemt niet weg dat [appellante] als de overwegend in het ongelijk gestelde partij moet worden aangemerkt. Dat geldt ook ten aanzien van de voorwaardelijk ingestelde vordering in reconventie nu [appellante] in eerste aanleg nog een bedrag vorderde van € 6.530,50 en zich niet heeft beperkt tot het bedrag van € 2.000,- dat volgens haar eigen stellingen in hoger beroep tussen partijen was afgesproken. 3.10.\\nHet bestreden vonnis zal worden vernietigd, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan € 13.000,-. Het hof zal in zoverre opnieuw recht doen.', 'beslissing': 'Het hof:\\n\\n\\n\\nvernietigt het vonnis waarvan beroep, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan € 13.000,-;\\n\\n\\n\\nin zoverre opnieuw rechtdoende:\\n\\n\\n\\nveroordeelt [appellante] tot betaling aan [geïntimeerde] van een bedrag van € 13.000,-, bepaalt dat voor “vijf maandelijkse termijnen van € 3.000,00” gelezen moet worden: vier maandelijkse termijnen van € 3.000,- en één termijn van € 1.000,- en wijst het meer gevorderde af;\\n\\n\\n\\nbekrachtigt het vonnis voor het overige;\\n\\n\\n\\nveroordeelt [appellante] in de kosten van het geding in hoger beroep, tot op heden aan de zijde van [geïntimeerde] begroot op € 704,- aan verschotten en € 894,- voor salaris;\\n\\n\\n\\nverklaart dit arrest uitvoerbaar bij voorraad.', 'materiele feiten': '3.1.\\nOp 10 oktober 2012 heeft [geïntimeerde] een bedrag van € 15.000,- ter leen verstrekt aan [appellante] in verband met het voornemen van [appellante] een onderneming (verkoop van voedingssupplementen) te beginnen. Op 4/5 januari 2013 heeft [appellante] een schriftelijke verklaring opgesteld, die beide partijen hebben ondertekend. 3.7.\\nUit de overeenkomst tussen partijen volgt dat [appellante] het geleende bedrag zal terugbetalen wanneer zij daartoe in staat zal zijn. Op basis van de wederzijdse stellingen van partijen kan worden aangenomen dat [appellante] geen inkomsten meer zal ontvangen uit haar onderneming. Uit haar eigen stellingen volgt dat zij eigenaar is van een woning.', 'proceshandelingen': '3.2.\\n\\n[geïntimeerde] vorderde in eerste aanleg (samengevat) nietigverklaring van de tussen partijen gesloten overeenkomst en veroordeling van [appellante] tot betaling van € 15.000,-. In voorwaardelijke reconventie vorderde [appellante] veroordeling van [geïntimeerde] tot betaling van € 6.530,50, te vermeerderen met wettelijke rente. Daarin klaagt [appellante] dat de kantonrechter niet heeft aangenomen dat [geïntimeerde] een doos met voedingssupplementen heeft besteld en afgenomen van haar. 3.6.\\nGrief 1 strekt ertoe dat het hof de terugbetalingstermijnen opnieuw zal vaststellen en daarbij rekening zal houden met de draagkracht van [appellante] . [appellante] wijst erop dat [geïntimeerde] op de hoogte was van haar financiële positie, wist waar [appellante] het geld voor zou gaan gebruiken en dat er dus een risico bestond dat zij geen omzet/winst zou maken. Zij brengt naar voren dat zij enkel inkomsten heeft uit haar AOW-uitkering van ongeveer € 950,- per maand en dat zij in termijnen van € 50,- zou kunnen terugbetalen. Executoriale verkoop van haar woning zou in de gegeven omstandigheden misbruik van executiebevoegdheid opleveren. 3.8.\\nIn grief 3 betoogt [appellante] dat de kantonrechter haar ten onrechte heeft veroordeeld in de proceskosten, zowel in conventie als in voorwaardelijke reconventie.'}

In [7]:
from bs4 import BeautifulSoup
import os
import pandas as pd

def extract_headers_and_sections_from_xml(xml_path, wanted_titles=None):
    """
    Extracts headers (section titles present in the full text) and their corresponding section texts from a Rechtspraak XML file.
    Returns:
        headers: list of section titles (headers) found in the text
        sections: list of dicts: {"title": title, "text": section_text}
    """
    with open(xml_path, 'r', encoding='utf-8') as f:
        soup = BeautifulSoup(f, 'xml')

    sections = []
    for sec in soup.find_all(lambda t: t.name and t.name.lower().endswith('section')):
        title_tag = sec.find(lambda t: t.name and t.name.lower().endswith('title'))
        nr_tag = title_tag.find(lambda t: t.name and t.name.lower().endswith('nr')) if title_tag else None
        nr = nr_tag.text.strip() if nr_tag else ""
        title_text = "".join(title_tag.stripped_strings) if title_tag else ""
        if nr:
            title_text = title_text.replace(nr, "", 1).strip()
        # Get all text in the section (excluding the title/nr)
        section_text = " ".join([s for s in sec.stripped_strings if s not in (nr, title_text)])
        sections.append({"title": title_text, "text": section_text})

    # If wanted_titles is provided, filter headers to only those present in the text
    if wanted_titles:
        wanted_set = set([t.strip().lower() for t in wanted_titles])
        headers = [s["title"] for s in sections if s["title"].strip().lower() in wanted_set]
        filtered_sections = [s for s in sections if s["title"].strip().lower() in wanted_set]
    else:
        headers = [s["title"] for s in sections if s["title"]]
        filtered_sections = [s for s in sections if s["title"]]

    return headers, filtered_sections


# ===========================
# BATCH EXTRACTION (dict form)
# ===========================

xml_folder = 'rechtspraak_xml'

def get_xml_path(ecli):
    ecli = ecli.replace('.txt', '')
    filename = ecli.replace(':', '_') + '.xml'
    return os.path.join(xml_folder, filename)

# Build a list of dicts instead of two separate lists
data = []
df_documents = pd.read_csv('datasets\\documents_raw.csv') 
for ecli in df_documents['doc_name']:
    xml_path = get_xml_path(ecli)
    if os.path.exists(xml_path):
        headers, sections = extract_headers_and_sections_from_xml(xml_path)

        # Convert to dict: { title: text }
        title_text_dict = {s["title"]: s["text"] for s in sections if s.get("title") and s.get("text")}

        data.append({
            "case_name": ecli,
            "extracted_data": title_text_dict
        })
    else:
        data.append({
            "case_name": ecli,
            "extracted_data": None
        })

# Build the final DataFrame
df_final = pd.DataFrame(data)
df_final = df_final[df_final['extracted_data'].apply(lambda d: isinstance(d, dict) and len(d) != 0)].reset_index(drop=True) # Keep only rows with non-empty dicts
df_final

,case_name,extracted_data
0,ECLI:NL:GHAMS:2015:2960.txt,{'Het geding in hoger beroep': 'Partijen worde...
1,ECLI:NL:GHAMS:2015:5282.txt,{'Het verloop van het geding': '1.1 In het ver...
2,ECLI:NL:GHARL:2016:7748.txt,{'Het verdere verloop van het geding in hoger ...
3,ECLI:NL:GHDHA:2016:706.txt,{'GERECHTSHOF DEN HAAG': 'Afdeling Civiel rech...
4,ECLI:NL:GHSHE:2021:1091.txt,"{'In eerste aanleg, hoger beroep en cassatie':..."
...,...,...
95,ECLI:NL:RBNNE:2018:4847.txt,{'Procesverloop': 'Bij besluit van 1 augustus ...
96,ECLI:NL:RBOBR:2019:10.txt,{'Procesverloop': 'Met het besluit van 22 dece...
97,ECLI:NL:RBOVE:2019:1349.txt,{'Procesverloop': 'Bij besluit van 7 mei 2018 ...
98,ECLI:NL:RBROT:2016:4797.txt,{'Procesverloop': 'Bij besluit van 28 november...
99,ECLI:NL:RBZWB:2015:638.txt,{'Procesverloop': 'Eiser heeft beroep ingestel...

In [8]:
## Remove unwanted titles and their sections from the extracted data ##

# Define title groups (section titles to remove)
# Each group contains possible variants/synonyms of a section title
title_groups = {
    "wettelijk_kader": [
        "wettelijk_kader", "toepasselijke wettelijke voorschriften", "de wettelijke voorschriften",
        "toepassende wetsbepalingen", "toepasselijke wetsartikelen", "de toegepaste wettelijke voorschriften",
        "de toepasselijke wetsartikelen", "de toegepaste wettelijke bepalingen"
    ],
    "proceskosten": [
        "proceskosten", "griffierecht en proceskosten", "kosten", "proceskosten en griffierecht"
    ],
    "procesverloop": 
    [
        "procesverloop", "de procedure", "het geding in hoger beroep", "het procesverloop",
        "het geding in eerste aanleg", "ontstaan en loop van het geding", "procesgang",
        "procesverloop in cassatie", "het verloop van de procedure", "procesverloop",
        "het verloop van het geding in eerste aanleg", "het verdere verloop van het geding in hoger beroep",
        "het verloop van het geding", "het verloop van de procedure in hoger beroep",
        "de procedure in hoger beroep", "procesverloop in hoger beroep", "procedure",
        "het verdere verloop van de procedure in hoger beroep", "het verdere verloop van de procedure",
        "de procedure bij de rechtbank", "de procedure in eerste aanleg", "verloop van de procedure",
        "het verdere procesverloop", "procedure bij de rechtbank", "het geschil en de beslissing in eerste aanleg"
    ],
}

import re

def normalize(s):
    """Normalize a title: collapse whitespace, strip and lowercase."""
    return re.sub(r"\s+", " ", (s or "")).strip().lower()

# Flatten to a set of normalized titles to remove
titles_to_remove = set(normalize(t) for vals in title_groups.values() for t in vals)
print(titles_to_remove)

### Remove specified titles from extracted data ###
list_removed = []
list_newd = []
for i,extracted_items in enumerate(df_final.extracted_data,start=1): 
    titles = list(extracted_items.keys())
    n_titles = [normalize(t) for t in titles]
    removed = {}
    for t in n_titles:
        if t in titles_to_remove:
            print(f"Case {i} - Will remove: {t}")
            removed[t] = extracted_items[titles[n_titles.index(t)]]
            extracted_items.pop(titles[n_titles.index(t)])
    list_removed.append(removed)
    list_newd.append(extracted_items if extracted_items else None)
df_final['removed_titles'] = list_removed
df_final

{'de toegepaste wettelijke bepalingen', 'de procedure bij de rechtbank', 'het verloop van de procedure in hoger beroep', 'toepasselijke wettelijke voorschriften', 'procedure', 'toepassende wetsbepalingen', 'het procesverloop', 'ontstaan en loop van het geding', 'de procedure in eerste aanleg', 'het verdere verloop van de procedure', 'het verloop van de procedure', 'procesverloop in cassatie', 'procedure bij de rechtbank', 'het verdere procesverloop', 'procesverloop', 'de procedure', 'toepasselijke wetsartikelen', 'proceskosten', 'procesgang', 'kosten', 'de toepasselijke wetsartikelen', 'het geding in eerste aanleg', 'het verloop van het geding in eerste aanleg', 'griffierecht en proceskosten', 'procesverloop in hoger beroep', 'de toegepaste wettelijke voorschriften', 'de procedure in hoger beroep', 'het geding in hoger beroep', 'het verloop van het geding', 'het verdere verloop van de procedure in hoger beroep', 'het verdere verloop van het geding in hoger beroep', 'de wettelijke voorschriften', 'verloop van de procedure', 'het geschil en de beslissing in eerste aanleg', 'wettelijk_kader', 'proceskosten en griffierecht'}
Case 1 - Will remove: het geding in hoger beroep
Case 2 - Will remove: het verloop van het geding
Case 3 - Will remove: het verdere verloop van het geding in hoger beroep
Case 7 - Will remove: de procedure
Case 9 - Will remove: de procedure
Case 10 - Will remove: de procedure
Case 11 - Will remove: het procesverloop
Case 12 - Will remove: de procedure
Case 13 - Will remove: procesverloop
Case 14 - Will remove: de procedure
Case 15 - Will remove: het verloop van de procedure
Case 16 - Will remove: de procedure
Case 17 - Will remove: de procedure
Case 18 - Will remove: toepasselijke wettelijke voorschriften
Case 20 - Will remove: toepasselijke wettelijke voorschriften
Case 25 - Will remove: de toepasselijke wetsartikelen
Case 26 - Will remove: de toegepaste wettelijke bepalingen
Case 27 - Will remove: de wettelijke voorschriften
Case 28 - Will remove: de procedure
Case 28 - Will remove: toepasselijke wettelijke voorschriften
Case 29 - Will remove: toepasselijke wettelijke voorschriften
Case 32 - Will remove: de toegepaste wettelijke voorschriften
Case 33 - Will remove: procesverloop
Case 34 - Will remove: de wettelijke voorschriften
Case 35 - Will remove: ontstaan en loop van het geding
Case 36 - Will remove: ontstaan en loop van het geding
Case 36 - Will remove: griffierecht en proceskosten
Case 37 - Will remove: procesverloop
Case 37 - Will remove: proceskosten en griffierecht
Case 38 - Will remove: ontstaan en loop van het geding
Case 39 - Will remove: proceskosten
Case 40 - Will remove: procesverloop
Case 41 - Will remove: procesverloop
Case 42 - Will remove: procesverloop
Case 43 - Will remove: procesverloop
Case 44 - Will remove: procesverloop
Case 45 - Will remove: procesverloop
Case 46 - Will remove: procesverloop
Case 47 - Will remove: procesverloop
Case 48 - Will remove: procesverloop
Case 49 - Will remove: procesverloop
Case 50 - Will remove: procesverloop
Case 51 - Will remove: het geding in hoger beroep
Case 52 - Will remove: het geding in hoger beroep
Case 53 - Will remove: het verdere verloop van het geding in hoger beroep
Case 54 - Will remove: procesverloop in hoger beroep
Case 55 - Will remove: het geding in eerste aanleg
Case 55 - Will remove: het geding in hoger beroep
Case 57 - Will remove: de procedure
Case 58 - Will remove: procedure
Case 59 - Will remove: de procedure
Case 61 - Will remove: de procedure
Case 62 - Will remove: het procesverloop
Case 64 - Will remove: het procesverloop
Case 65 - Will remove: de procedure
Case 66 - Will remove: de procedure
Case 67 - Will remove: de procedure
Case 69 - Will remove: toepasselijke wettelijke voorschriften
Case 70 - Will remove: toepasselijke wettelijke voorschriften
Case 74 - Will remove: toepasselijke wettelijke voorschriften
Case 75 - Will remove: de toepasselijke wetsartikelen
Case 76 - Will remove: de toegepaste wettelijke bepalingen
Case 77 - Will remove: de wettelijke voorschriften
Case 79 - Will remove: toepasselijke wettelijke voorschriften
Case 82 - Will remove: de toegepaste wettelijke voorschriften
Case 84 - Will remove: de wettelijke voorschriften
Case 85 - Will remove: ontstaan en loop van het geding
Case 86 - Will remove: ontstaan en loop van het geding
Case 86 - Will remove: griffierecht en proceskosten
Case 87 - Will remove: procesverloop
Case 87 - Will remove: proceskosten en griffierecht
Case 88 - Will remove: ontstaan en loop van het geding
Case 90 - Will remove: procesgang
Case 90 - Will remove: toepasselijke wetsartikelen
Case 91 - Will remove: procesverloop
Case 92 - Will remove: procesverloop
Case 93 - Will remove: procesverloop
Case 94 - Will remove: procesverloop
Case 95 - Will remove: procesverloop
Case 96 - Will remove: procesverloop
Case 97 - Will remove: procesverloop
Case 98 - Will remove: procesverloop
Case 99 - Will remove: procesverloop
Case 100 - Will remove: procesverloop

,case_name,extracted_data,removed_titles
0,ECLI:NL:GHAMS:2015:2960.txt,{'Feiten': 'De kantonrechter heeft in het best...,{'het geding in hoger beroep': 'Partijen worde...
1,ECLI:NL:GHAMS:2015:5282.txt,{'De gronden van de beslissing': 'Nu van de zi...,{'het verloop van het geding': '1.1 In het ver...
2,ECLI:NL:GHARL:2016:7748.txt,{'De verdere motivering van de beslissing in h...,{'het verdere verloop van het geding in hoger ...
3,ECLI:NL:GHDHA:2016:706.txt,{'GERECHTSHOF DEN HAAG': 'Afdeling Civiel rech...,{}
4,ECLI:NL:GHSHE:2021:1091.txt,"{'In eerste aanleg, hoger beroep en cassatie':...",{}
...,...,...,...
95,ECLI:NL:RBNNE:2018:4847.txt,{'Overwegingen': '1. De rechtbank gaat uit van...,{'procesverloop': 'Bij besluit van 1 augustus ...
96,ECLI:NL:RBOBR:2019:10.txt,{'Overwegingen': 'De aanleiding voor deze proc...,{'procesverloop': 'Met het besluit van 22 dece...
97,ECLI:NL:RBOVE:2019:1349.txt,{'Overwegingen': '1.Op 15 oktober 2017 heeft e...,{'procesverloop': 'Bij besluit van 7 mei 2018 ...
98,ECLI:NL:RBROT:2016:4797.txt,{'Overwegingen': '1. Verweerder heeft aan het ...,{'procesverloop': 'Bij besluit van 28 november...
99,ECLI:NL:RBZWB:2015:638.txt,{'Overwegingen': '1. Op grond van de stukken e...,{'procesverloop': 'Eiser heeft beroep ingestel...

In [9]:
SEED_WORDS_LIST = {
    "Context": [
        "context_overig", "voorvragen", "de voorvragen", "inleiding", "grondslag en inhoud van het eab",
        "onderzoek van de zaak", "het onderzoek ter terechtzitting", "onderzoek ter terechtzitting", "gronden",
        "het onderzoek op de terechtzitting", "onderzoek op de terechtzitting", "de kern van de zaak",
        "waar gaat deze zaak over?", "inleiding en samenvatting", "waar gaat het over?", "het bewijs",
        "waar gaat de zaak over?"
    ],
    "Feiten": [
        "feiten", "de feiten", "feiten", "de zaak in het kort", "de vaststaande feiten", "vaststaande feiten",
        "uitgangspunten en feiten", "feiten en procesverloop", "feitelijke achtergrond", "uitgangspunten in cassatie"
    ],
    "Beoordeling": [
        "beoordeling_door_rechter", "de beoordeling", "waardering van het bewijs", "de motivering van de beslissing",
        "beoordeling", "bewezenverklaring", "de beoordeling van het bewijs", "de verdere beoordeling",
        "beoordeling van het geschil", "de strafbaarheid van de verdachte", "strafbaarheid van verdachte",
        "de strafbaarheid van verdachte", "de strafbaarheid", "beoordeling door de rechtbank", "strafbaarheid",
        "beoordeling van het middel", "strafbaarheid van de feiten", "de strafbaarheid van het bewezenverklaarde",
        "conclusie en gevolgen", "de bewezenverklaring", "de strafbaarheid van de feiten",
        "de strafbaarheid van het bewezen verklaarde", "beoordeling van het cassatiemiddel",
        "beoordeling van de middelen", "bespreking van het cassatiemiddel", "de bewijsmotivering",
        "beoordeling van het bewijs", "strafbaarheid verdachte", "de motivering van de beslissing in hoger beroep",
        "beoordeling van de ontvankelijkheid van het beroep in cassatie", "de bewijsbeslissing",
        "de kwalificatie van het bewezenverklaarde", "strafbaarheid van de verdachte", "de gronden van de beslissing",
        "motivering van de straf", "de strafbaarheid van het feit", "de beoordeling van het geschil",
        "strafbaarheid van het feit", "motivering straf", "motivering van de sanctie", "het oordeel van de rechtbank",
        "de beoordeling in het incident", "beoordeling van de klachten", "de beoordeling in hoger beroep",
        "overwegingen", "kwalificatie en strafbaarheid van de feiten", "beoordeling van de cassatiemiddelen",
        "beoordeling van het eerste cassatiemiddel", "strafbaarheid feiten",
        "de overwegingen ten aanzien van straf en/of maatregel", "beoordeling van het tweede cassatiemiddel",
        "beoordeling in hoger beroep", "strafbaarheid feit", "motivering van de straffen en maatregelen",
        "kwalificatie en strafbaarheid van het feit", "de beoordeling in conventie en in reconventie",
        "het geschil in reconventie", "de straf en/of de maatregel", "bewijs", "het eerste middel",
        "de beoordeling van de civiele vordering"
    ],
    "Beslissing": [
        "beslissing", "de beslissing", "beslissing", "slotsom", "de uitspraak", "de slotsom", "de strafoplegging",
        "conclusie", "oplegging van straf", "de op te leggen straf of maatregel", "vrijspraak", ".beslissing",
        ". beslissing", "de straf"
    ],
    "Proceshandelingen partijen": [
        "proceshandelingen_partijen", "het geschil", "tenlastelegging", "de tenlastelegging", "de vordering",
        "het verweer", "het verzoek", "geschil", "geding in cassatie", "eis officier van justitie",
        "de vordering en het verweer", "de inhoud van de tenlastelegging", "het wrakingsverzoek",
        "geschil in hoger beroep", "het verzoek en het verweer", "geschil en conclusies van partijen",
        "het cassatieberoep", "het geschil in conventie", "de standpunten", "standpunten van partijen",
        "het standpunt van de officier van justitie", "de vordering tot tenuitvoerlegging"
    ]
}

In [10]:
import re
import os
import pandas as pd
from collections import defaultdict

# Try RapidFuzz; fallback to difflib if not installed
try:
    from rapidfuzz import fuzz
    _HAS_RAPIDFUZZ = True
except ImportError:
    import difflib
    _HAS_RAPIDFUZZ = False


# -------------------------
# Normalization + tokens
# -------------------------
DUTCH_STOP_TOKENS = {
    "de","het","een","en","van","in","op","aan","bij","voor","met","tot","uit","door",
    "over","onder","naar","als","is","zijn","wordt","werden","was","dat","die","dit",
    "te","ten","ter","der","den","of","maar","ook","nog","dan","wel","niet"
}

def normalize_header(s: str) -> str:
    if not isinstance(s, str):
        return ""
    s = s.strip().lower()
    s = re.sub(r"\s+", " ", s).strip()
    s = s.strip(" .:-–—\t")
    return s

def tokenize_for_match(s: str):
    s = normalize_header(s)
    toks = re.findall(r"[a-z0-9]+", s)
    toks = [t for t in toks if t not in DUTCH_STOP_TOKENS]
    return toks


# -------------------------
# REMOVE UNWANTED TITLES
# -------------------------
# Define title groups (section titles to remove)
title_groups = {
    "wettelijk_kader": [
        "wettelijk_kader", "toepasselijke wettelijke voorschriften", "de wettelijke voorschriften",
        "toepassende wetsbepalingen", "toepasselijke wetsartikelen", "de toegepaste wettelijke voorschriften",
        "de toepasselijke wetsartikelen", "de toegepaste wettelijke bepalingen"
    ],
    "proceskosten": [
        "proceskosten", "griffierecht en proceskosten", "kosten", "proceskosten en griffierecht"
    ],
    "procesverloop": [
        "procesverloop", "de procedure", "het geding in hoger beroep", "het procesverloop",
        "het geding in eerste aanleg", "ontstaan en loop van het geding", "procesgang",
        "procesverloop in cassatie", "het verloop van de procedure", "procesverloop",
        "het verloop van het geding in eerste aanleg", "het verdere verloop van het geding in hoger beroep",
        "het verloop van het geding", "het verloop van de procedure in hoger beroep",
        "de procedure in hoger beroep", "procesverloop in hoger beroep", "procedure",
        "het verdere verloop van de procedure in hoger beroep", "het verdere verloop van de procedure",
        "de procedure bij de rechtbank", "de procedure in eerste aanleg", "verloop van de procedure",
        "het verdere procesverloop", "procedure bij de rechtbank", "het geschil en de beslissing in eerste aanleg"
    ],
}

def build_remove_title_set(title_groups: dict) -> set:
    remove_set = set()
    for _, variants in title_groups.items():
        if not isinstance(variants, (list, tuple)):
            continue
        for v in variants:
            if isinstance(v, str):
                nv = normalize_header(v)
                if nv:
                    remove_set.add(nv)
    return remove_set

REMOVE_TITLE_SET = build_remove_title_set(title_groups)

def is_unwanted_title(title: str) -> bool:
    return normalize_header(title) in REMOVE_TITLE_SET


# -------------------------
# Seed structures
# -------------------------
def build_seed_structures(seed_dict):
    """
    seed_dict: {group_name: [phrases...]}

    Returns:
      exact_map: norm_phrase -> group_name
      group_phrase_tokens: group_name -> list of (norm_phrase, token_set)
      all_seed_phrases: list of (group_name, norm_phrase)
      seed_phrase_tokens_flat: list of (group_name, norm_phrase, token_set)
    """
    exact_map = {}
    group_phrase_tokens = defaultdict(list)
    all_seed_phrases = []
    seed_phrase_tokens_flat = []

    for group_name, phrases in seed_dict.items():
        if not isinstance(phrases, (list, tuple)):
            continue

        for phrase in phrases:
            if not isinstance(phrase, str):
                continue

            norm_phrase = normalize_header(phrase)
            if not norm_phrase:
                continue

            # exact map (first occurrence wins)
            if norm_phrase not in exact_map:
                exact_map[norm_phrase] = group_name

            tok_set = set(tokenize_for_match(phrase))
            if tok_set:
                group_phrase_tokens[group_name].append((norm_phrase, tok_set))
                seed_phrase_tokens_flat.append((group_name, norm_phrase, tok_set))

            all_seed_phrases.append((group_name, norm_phrase))

    return exact_map, group_phrase_tokens, all_seed_phrases, seed_phrase_tokens_flat


EXACT_SEED_MAP, GROUP_PHRASE_TOKENS, ALL_SEED_PHRASES, SEED_PHRASE_TOKENS_FLAT = build_seed_structures(SEED_WORDS_LIST)


# -------------------------
# Matching: exact → token overlap → fuzzy
# -------------------------
def token_overlap_match(title: str, min_overlap_tokens: int = 2, min_jaccard: float = 0.34):
    title_tokens = set(tokenize_for_match(title))
    if not title_tokens:
        return (False, None, {})

    best = None
    for group_name, phrase_list in GROUP_PHRASE_TOKENS.items():
        for seed_phrase, seed_tokens in phrase_list:
            inter = title_tokens & seed_tokens
            overlap = len(inter)
            if overlap == 0:
                continue

            union = len(title_tokens | seed_tokens)
            jacc = overlap / union if union else 0.0

            cand = (overlap, jacc, group_name, seed_phrase, inter)
            if best is None or (cand[0], cand[1]) > (best[0], best[1]):
                best = cand

    if best is None:
        return (False, None, {})

    overlap, jacc, group_name, seed_phrase, inter = best
    if overlap >= min_overlap_tokens and jacc >= min_jaccard:
        return (True, group_name, {
            "best_seed": seed_phrase,
            "overlap": overlap,
            "jaccard": jacc,
            "shared_tokens": sorted(list(inter))
        })

    return (False, None, {
        "best_seed": seed_phrase,
        "overlap": overlap,
        "jaccard": jacc,
        "shared_tokens": sorted(list(inter))
    })


def _fuzzy_score(a: str, b: str) -> float:
    if _HAS_RAPIDFUZZ:
        return float(fuzz.token_set_ratio(a, b))
    else:
        return float(difflib.SequenceMatcher(None, a, b).ratio() * 100.0)


def fuzzy_match(title: str,
                min_score: float = 90.0,
                min_title_len: int = 8,
                require_token_overlap: bool = True,
                min_overlap_for_fuzzy: int = 1):
    norm_title = normalize_header(title)
    if len(norm_title) < min_title_len:
        return (False, None, {"reason": "title_too_short", "norm_title": norm_title})

    title_tokens = set(tokenize_for_match(title))

    best = None
    for group_name, seed_phrase in ALL_SEED_PHRASES:
        score = _fuzzy_score(norm_title, seed_phrase)
        if best is None or score > best[0]:
            best = (score, group_name, seed_phrase)

    if best is None:
        return (False, None, {"reason": "no_seeds", "norm_title": norm_title})

    score, group_name, seed_phrase = best

    debug = {"norm_title": norm_title, "best_seed": seed_phrase, "score": score}

    if score < min_score:
        debug["reason"] = "score_below_threshold"
        return (False, None, debug)

    if require_token_overlap:
        seed_tokens = set(tokenize_for_match(seed_phrase))
        inter = title_tokens & seed_tokens
        debug["shared_tokens"] = sorted(list(inter))
        debug["overlap"] = len(inter)
        if len(inter) < min_overlap_for_fuzzy:
            debug["reason"] = "no_token_overlap_with_best_seed"
            return (False, None, debug)

    return (True, group_name, debug)


def match_group_cascade(title: str,
                        token_min_overlap: int = 2,
                        token_min_jaccard: float = 0.34,
                        fuzzy_min_score: float = 90.0,
                        fuzzy_min_title_len: int = 8,
                        fuzzy_require_token_overlap: bool = True,
                        fuzzy_min_overlap: int = 1):
    norm_title = normalize_header(title)
    if not norm_title:
        return (False, None, norm_title, None, {})

    # 1) Exact
    group = EXACT_SEED_MAP.get(norm_title)
    if group is not None:
        return (True, group, norm_title, "exact", {"norm_title": norm_title})

    # 2) Token overlap
    ok2, group2, dbg2 = token_overlap_match(title,
                                            min_overlap_tokens=token_min_overlap,
                                            min_jaccard=token_min_jaccard)
    if ok2:
        dbg2["norm_title"] = norm_title
        return (True, group2, norm_title, "token_overlap", dbg2)

    # 3) Fuzzy
    ok3, group3, dbg3 = fuzzy_match(title,
                                    min_score=fuzzy_min_score,
                                    min_title_len=fuzzy_min_title_len,
                                    require_token_overlap=fuzzy_require_token_overlap,
                                    min_overlap_for_fuzzy=fuzzy_min_overlap)
    if ok3:
        return (True, group3, norm_title, "fuzzy", dbg3)

    return (False, None, norm_title, None, {"norm_title": norm_title})


# -------------------------
# Main extraction loop + audits + unmatched + removed
# -------------------------
filtered_rows = []

token_overlap_audit_rows = []
fuzzy_audit_rows = []

unmatched_by_case = defaultdict(list)
unmatched_rows = []

# optional: track removed titles
removed_rows = []

for ecli in df_documents["doc_name"]:
    xml_path = get_xml_path(ecli)
    if not os.path.exists(xml_path):
        continue

    headers, sections = extract_headers_and_sections_from_xml(xml_path, wanted_titles=None)

    kept = []
    for s in sections:
        title = s.get("title", "")
        text = s.get("text", "")
        norm_title = normalize_header(title)

        # ---- REMOVE unwanted sections BEFORE matching ----
        if title and norm_title and is_unwanted_title(title):
            removed_rows.append({
                "case_name": ecli,
                "title": title,
                "norm_title": norm_title,
                "section_text_snippet": (text or "")[:200]
            })
            continue

        ok, group_name, norm_title, method, debug = match_group_cascade(
            title,
            token_min_overlap=2,
            token_min_jaccard=0.34,
            fuzzy_min_score=80.0,
            fuzzy_min_title_len=8,
            fuzzy_require_token_overlap=True,
            fuzzy_min_overlap=1
        )

        if ok:
            kept.append({
                "title": title,
                "text": text,
                "hdr_group": group_name,
                "norm_title": norm_title,
                "match_method": method,
                "match_debug": debug
            })

            if method == "token_overlap":
                token_overlap_audit_rows.append({
                    "case_name": ecli,
                    "original_title": title,
                    "normalized_title": norm_title,
                    "assigned_group": group_name,
                    "best_seed": debug.get("best_seed"),
                    "shared_tokens": debug.get("shared_tokens"),
                    "overlap": debug.get("overlap"),
                    "jaccard": debug.get("jaccard"),
                    "section_text_snippet": (text or "")[:300]
                })

            elif method == "fuzzy":
                fuzzy_audit_rows.append({
                    "case_name": ecli,
                    "original_title": title,
                    "normalized_title": norm_title,
                    "assigned_group": group_name,
                    "best_seed": debug.get("best_seed"),
                    "fuzzy_score": debug.get("score"),
                    "shared_tokens": debug.get("shared_tokens"),
                    "overlap": debug.get("overlap"),
                    "section_text_snippet": (text or "")[:300],
                    "used_rapidfuzz": _HAS_RAPIDFUZZ
                })

        else:
            if title and norm_title:
                entry = {
                    "title": title,
                    "norm_title": norm_title,
                    "section_text_snippet": (text or "")[:300],
                }
                unmatched_by_case[ecli].append(entry)
                unmatched_rows.append({"case_name": ecli, **entry})

    if kept:
        title_text_dict = {k["title"]: k["text"] for k in kept if k["title"] and k["text"]}
        filtered_rows.append({
            "case_name": ecli,
            "extracted_data": title_text_dict,
            "matched_headers": [k["title"] for k in kept],
            "matched_groups": [k["hdr_group"] for k in kept],
            "matched_norm_titles": [k["norm_title"] for k in kept],
            "match_methods": [k["match_method"] for k in kept],
        })

df_filtered_cascade = pd.DataFrame(filtered_rows).reset_index(drop=True)
df_token_overlap_audit = pd.DataFrame(token_overlap_audit_rows)
df_fuzzy_audit = pd.DataFrame(fuzzy_audit_rows)
df_unmatched = pd.DataFrame(unmatched_rows).reset_index(drop=True)
df_removed = pd.DataFrame(removed_rows).reset_index(drop=True)

print("Cases with ≥1 unmatched header:", len(unmatched_by_case))
print("Total unmatched headers:", len(df_unmatched))
print("Total removed sections:", len(df_removed))

df_filtered_cascade, df_token_overlap_audit, df_fuzzy_audit, df_unmatched, df_removed

df_filtered_cascade['number_of_headers'] = df_filtered_cascade.matched_headers.apply(lambda d: len(d))
df_filtered_cascade

Cases with ≥1 unmatched header: 62
Total unmatched headers: 128
Total removed sections: 86

,case_name,extracted_data,matched_headers,matched_groups,matched_norm_titles,match_methods,number_of_headers
0,ECLI:NL:GHAMS:2015:2960.txt,{'Feiten': 'De kantonrechter heeft in het best...,"[Feiten, Beoordeling, Beslissing]","[Feiten, Beoordeling, Beslissing]","[feiten, beoordeling, beslissing]","[exact, exact, exact]",3
1,ECLI:NL:GHAMS:2015:5282.txt,{'De gronden van de beslissing': 'Nu van de zi...,"[De gronden van de beslissing, De beslissing]","[Beoordeling, Beslissing]","[de gronden van de beslissing, de beslissing]","[exact, exact]",2
2,ECLI:NL:GHARL:2016:7748.txt,{'De verdere motivering van de beslissing in h...,[De verdere motivering van de beslissing in ho...,"[Beoordeling, Beslissing]",[de verdere motivering van de beslissing in ho...,"[token_overlap, exact]",2
3,ECLI:NL:GHDHA:2016:706.txt,{'Inhoudelijke beoordeling': '45. Op 1 januari...,"[Inhoudelijke beoordeling, Inhoudelijke beoord...","[Beoordeling, Beoordeling, Beoordeling, Beoord...","[inhoudelijke beoordeling, inhoudelijke beoord...","[fuzzy, fuzzy, fuzzy, fuzzy, fuzzy, fuzzy, fuzzy]",7
4,ECLI:NL:GHSHE:2021:1091.txt,{'De beoordeling': '2.1. De Hoge Raad heeft in...,"[De beoordeling, De uitspraak]","[Beoordeling, Beslissing]","[de beoordeling, de uitspraak]","[exact, exact]",2
...,...,...,...,...,...,...,...
95,ECLI:NL:RBNNE:2018:4847.txt,{'Overwegingen': '1. De rechtbank gaat uit van...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2
96,ECLI:NL:RBOBR:2019:10.txt,{'Overwegingen': 'De aanleiding voor deze proc...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2
97,ECLI:NL:RBOVE:2019:1349.txt,{'Overwegingen': '1.Op 15 oktober 2017 heeft e...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2
98,ECLI:NL:RBROT:2016:4797.txt,{'Overwegingen': '1. Verweerder heeft aan het ...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2
99,ECLI:NL:RBZWB:2015:638.txt,{'Overwegingen': '1. Op grond van de stukken e...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2

In [11]:
# Unique headers (original titles)
unique_headers = (
    df_filtered_cascade["matched_norm_titles"]
    .explode()
    .dropna()
    .sort_values()
    .unique()
)

print(f"Number of unique headers: {len(unique_headers)}")
unique_headers

Number of unique headers: 143

array(['6. beslissing',
       'aan de beoordeling van het middel voorafgaande opmerkingen',
       'beoordeling', 'beoordeling van de middelen',
       'beoordeling van de vordering', 'beoordeling van het bewijs',
       'beoordeling van het geschil', 'beoordeling van het hoger beroep',
       'beoordeling van het middel',
       'beoordeling van het middel in het incidentele beroep',
       'beoordeling van het middel in het principale beroep',
       'beschikking op het verzoek van', 'beslissing',
       'beslissing op de vordering van de benadeelde partij [slachtoffer 2]',
       'beslissing op de vordering van de benadeelde partij [slachtoffer 3]',
       'beslissing op het hoger beroep', 'bewezenverklaring',
       'bewezenverklaring en bewijsvoering', 'bewijs',
       'bewijsoverweging ten aanzien van de feiten 1 en 2',
       'de beoordeling', 'de beoordeling in conventie',
       'de beoordeling in conventie en in reconventie',
       'de beoordeling in reconventie', 'de beoordeling van het bewijs',
       'de beslissing', 'de bewezenverklaring',
       'de eis van de officier van justitie', 'de feiten',
       'de feiten en de rechtsgang', 'de formele voorvragen',
       'de gronden van de beslissing', 'de inhoud van de tenlastelegging',
       'de kwalificatie van het bewezenverklaarde',
       'de ontvankelijkheid van de officier van justitie in haar vordering',
       'de ontvankelijkheid van het beroep',
       'de op te leggen straf of maatregel', 'de relevante feiten',
       'de standpunten', 'de standpunten ter zitting', 'de straf',
       'de straf en/of de maatregel', 'de strafbaarheid',
       'de strafbaarheid van de feiten',
       'de strafbaarheid van de verdachte',
       'de strafbaarheid van het bewezen verklaarde',
       'de strafbaarheid van het bewezenverklaarde',
       'de strafbaarheid van het bewezenverklaarde en de verdachte',
       'de strafbaarheid van het feit',
       'de strafbaarheid van het feit en van verdachte',
       'de strafbaarheid van verdachte', 'de strafoplegging',
       'de tenlastelegging', 'de uitspraak',
       'de uitspraak van de rechtbank luidt', 'de vaststaande feiten',
       'de verdere beoordeling',
       'de verdere motivering van de beslissing in hoger beroep',
       'de voorvragen', 'de vordering in conventie',
       'de vordering in de hoofdzaak', 'de vordering in reconventie',
       'de vordering tenuitvoerlegging',
       'de vordering tot tenuitvoerlegging',
       'de vordering van de benadeelde partij',
       'de vordering van de benadeelde partij / de schadevergoedingsmaatregel',
       'de vordering van de benadeelde partij [slachtoffer 2] . de rechtbank acht toewijsbaar, als rechtstreeks door het bewezen verklaarde feit toegebrachte schade, de volgende onderdelen van de vordering te weten immateriële schadevergoeding € 250,-- en materiële schadevergoeding van € 7,78 vermeerderd met de wettelijke rente vanaf 23 mei 2015 tot aan de dag der algehele voldoening',
       'de vordering van de benadeelde partij [slachtoffer 3] . de rechtbank acht toewijsbaar, als rechtstreeks door het bewezen verklaarde feit toegebrachte schade, de volgende onderdelen van de vordering te weten immateriële schadevergoeding € 250,-- en materiële schadevergoeding van € 7,78 vermeerderd met de wettelijke rente vanaf 23 mei 2015 tot aan de dag der algehele voldoening',
       'eis officier van justitie', 'feiten',
       'feiten waarvoor de toetsing van dubbele strafbaarheid is vereist',
       'geding in cassatie', 'geschil', 'geschil in hoger beroep',
       'geschil, alsmede standpunten en conclusies van partijen',
       'geschil11. in geschil is de hoogte van de verschuldigde overdrachtsbelasting. meer specifiek is in geschil of de artikelen 7 en 12 van de wet brv, dan wel de zogenoemde ‘doorkijkarresten’ van de hoge raad van 23 februari 2007 (nr. 41591, ecli:nl:hr2007:au8559) en van 10 juni 2011 (nr. 10/00498, ecli:nl:hr:2011:bq7580) toepassing vinden',
       'gronden', 'grondslag en inhoud van het eab',
       'het geding in cassatie', 'het geschil',
       'het geschil en de beoordeling in het incident',
       'het geschil in hoger beroep',
       'het geschil, de standpunten en conclusies van partijen',
       'het hoger beroep', 'het onderzoek op de terechtzitting',
       'het onderzoek ter terechtzitting', 'het oordeel van de rechtbank',
       'het standpunt van [a]',
       'het standpunt van de officier van justitie.de officier van justitie acht het onder feit 1 primair, feit 2 en feit 3 ten laste gelegde wettig en overtuigend bewezen',
       'het verweer', 'het verweer in reconventie', 'het verzoek',
       'het verzoek en de beoordeling', 'het verzoek om aanhouding',
       'inhoudelijke beoordeling',
       'kwalificatie en strafbaarheid van de feiten',
       'kwalificatie en strafbaarheid van het feit',
       'kwalificatie van het bewezen verklaarde',
       'motivering van de sanctie', 'motivering van de sancties',
       'motivering van de straffen en maatregelen',
       'omschrijving geschil in hoger beroep en conclusies van partijen',
       'omschrijving geschil na verwijzing en conclusies van partijen',
       'onderzoek op de terechtzitting', 'onderzoek ter terechtzitting',
       'onderzoek van de zaak', 'oordeel van de rechtbank',
       'oplegging van straf', 'oplegging van straf en maatregel',
       'oplegging van straf en/of maatregel', 'oplegging van straffen',
       'overwegingen',
       'overwegingen ten aanzien van straf en/of maatregel',
       'procesverloop in eerste aanleg en vaststaande feiten',
       'redengeving bewezenverklaring', 'slotsom', 'standpunt van de man',
       'standpunt van de vrouw', 'strafbaarheid van de verdachte',
       'strafbaarheid van het bewezen verklaarde',
       'strafbaarheid van het bewezenverklaarde',
       'strafbaarheid van verdachte', 'ten aanzien van feit 2',
       'ten aanzien van feit 3', 'tenlastelegging',
       'uitgangspunten in cassatie', 'vaststaande feiten', 'voorvragen',
       'vordering',
       'vordering benadeelde partij en schadevergoedingsmaatregel',
       'vordering officier van justitie', 'vordering tenuitvoerlegging',
       'vordering tot tenuitvoerlegging',
       'vordering van de benadeelde partij [benadeelde partij 1]',
       'vordering van de benadeelde partij [benadeelde partij 2]',
       'vordering van de benadeelde partij [benadeelde partij 3]',
       'vordering van de benadeelde partij [benadeelde partij 4]',
       'vordering van de benadeelde partij [benadeelde partij 5]',
       'vordering van de benadeelde partij [benadeelde partij]',
       'vordering van de benadeelde partij [benadeelde]',
       'vordering van het openbaar ministerie', 'vrijspraak',
       'waardering van het bewijs'], dtype=object)

In [12]:
unique_header_groups = (
    df_filtered_cascade["matched_groups"]
    .explode()
    .dropna()
    .sort_values()
    .unique()
)

print(f"Number of unique header groups: {len(unique_header_groups)}")
unique_header_groups

Number of unique header groups: 5

array(['Beoordeling', 'Beslissing', 'Context', 'Feiten',
       'Proceshandelingen partijen'], dtype=object)

In [13]:
header_group_map = (
    df_filtered_cascade
    .explode(["matched_headers", "matched_groups"])
    .loc[:, ["matched_headers", "matched_groups"]]
    .drop_duplicates()
    .sort_values(["matched_groups", "matched_headers"])
    .reset_index(drop=True)
)

header_group_map

header_group_dict = (
    df_filtered_cascade
    .explode(["matched_headers", "matched_groups"])
    .loc[:, ["matched_headers", "matched_groups"]]
    .drop_duplicates()
    .groupby("matched_groups")["matched_headers"]
    .apply(lambda x: sorted(x.unique()))
    .to_dict()
)

header_group_dict

{'Beoordeling': ['Aan de beoordeling van het middel voorafgaande opmerkingen',
  'BEOORDELING VAN DE VORDERING',
  'BEOORDELING VAN HET HOGER BEROEP',
  'BESLISSING OP HET HOGER BEROEP',
  'Beoordeling',
  'Beoordeling van de middelen',
  'Beoordeling van het bewijs',
  'Beoordeling van het geschil',
  'Beoordeling van het hoger beroep',
  'Beoordeling van het middel',
  'Beoordeling van het middel in het incidentele beroep',
  'Beoordeling van het middel in het principale beroep',
  'Bewezenverklaring',
  'Bewezenverklaring en bewijsvoering',
  'Bewijs',
  'De beoordeling',
  'De beoordeling in conventie',
  'De beoordeling in conventie en in reconventie',
  'De beoordeling in reconventie',
  'De beoordeling van het bewijs',
  'De bewezenverklaring',
  'De bewezenverklaring.',
  'De gronden van de beslissing',
  'De kwalificatie van het bewezenverklaarde',
  'De ontvankelijkheid van het beroep',
  'De straf en/of de maatregel',
  'De strafbaarheid',
  'De strafbaarheid van de feiten',
  'De strafbaarheid van de verdachte',
  'De strafbaarheid van het bewezen verklaarde',
  'De strafbaarheid van het bewezenverklaarde',
  'De strafbaarheid van het bewezenverklaarde en de verdachte',
  'De strafbaarheid van het feit',
  'De strafbaarheid van het feit en van verdachte',
  'De strafbaarheid van het feit.',
  'De strafbaarheid van verdachte',
  'De strafbaarheid van verdachte.',
  'De verdere beoordeling',
  'De verdere motivering van de beslissing in hoger beroep',
  'Het geschil en de beoordeling in het incident',
  'Het hoger beroep',
  'Het oordeel van de rechtbank.',
  'Het verzoek en de beoordeling',
  'Inhoudelijke beoordeling',
  'Kwalificatie en strafbaarheid van de feiten',
  'Kwalificatie en strafbaarheid van het feit',
  'Kwalificatie van het bewezen verklaarde',
  'Motivering van de sanctie',
  'Motivering van de sancties',
  'Motivering van de straffen en maatregelen',
  'Oordeel van de Rechtbank',
  'Oplegging van straf en maatregel.',
  'Oplegging van straf en/of maatregel.',
  'Overwegingen',
  'Overwegingen ten aanzien van straf en/of maatregel',
  'Redengeving bewezenverklaring',
  'Strafbaarheid van de verdachte',
  'Strafbaarheid van het bewezen verklaarde',
  'Strafbaarheid van het bewezenverklaarde',
  'Strafbaarheid van verdachte',
  'Ten aanzien van feit 2.',
  'Ten aanzien van feit 3.',
  'VORDERING',
  'Waardering van het bewijs'],
 'Beslissing': ['6. Beslissing',
  'BESLISSING',
  'Beslissing',
  'Beslissing op de vordering van de benadeelde partij [slachtoffer 2] :',
  'Beslissing op de vordering van de benadeelde partij [slachtoffer 3] :',
  'DE UITSPRAAK',
  'DE UITSPRAAK VAN DE RECHTBANK LUIDT:',
  'De beslissing',
  'De op te leggen straf of maatregel',
  'De straf',
  'De strafoplegging',
  'De uitspraak',
  'Oplegging van straf',
  'Oplegging van straffen',
  'Slotsom',
  'Vrijspraak'],
 'Context': ['De formele voorvragen.',
  'De voorvragen',
  'Gronden',
  'Grondslag en inhoud van het EAB',
  'Het onderzoek op de terechtzitting',
  'Het onderzoek ter terechtzitting',
  'ONDERZOEK TER TERECHTZITTING',
  'Onderzoek op de terechtzitting',
  'Onderzoek van de zaak',
  'Voorvragen'],
 'Feiten': ['Bewijsoverweging ten aanzien van de feiten 1 en 2.',
  'De feiten',
  'De feiten en de rechtsgang',
  'De relevante feiten',
  'De vaststaande feiten',
  'Feiten',
  'Feiten waarvoor de toetsing van dubbele strafbaarheid is vereist',
  'PROCESVERLOOP IN EERSTE AANLEG EN VASTSTAANDE FEITEN',
  'Uitgangspunten in cassatie',
  'Vaststaande feiten'],
 'Proceshandelingen partijen': ['Beschikking op het verzoek van:',
  'De eis van de officier van justitie.',
  'De inhoud van de tenlastelegging',
  'De ontvankelijkheid van de officier van justitie in haar vordering',
  'De standpunten',
  'De standpunten ter zitting',
  'De tenlastelegging',
  'De tenlastelegging.',
  'De vordering in conventie',
  'De vordering in de hoofdzaak',
  'De vordering in reconventie',
  'De vordering tenuitvoerlegging',
  'De vordering tot tenuitvoerlegging',
  'De vordering van de benadeelde partij',
  'De vordering van de benadeelde partij / de schadevergoedingsmaatregel',
  'De vordering van de benadeelde partij [slachtoffer 2] . De rechtbank acht toewijsbaar, als rechtstreeks door het bewezen verklaarde feit toegebrachte schade, de volgende onderdelen van de vordering te weten immateriële schadevergoeding € 250,-- en materiële schadevergoeding van € 7,78 vermeerderd met de wettelijke rente vanaf 23 mei 2015 tot aan de dag der algehele voldoening.',
  'De vordering van de benadeelde partij [slachtoffer 3] . De rechtbank acht toewijsbaar, als rechtstreeks door het bewezen verklaarde feit toegebrachte schade, de volgende onderdelen van de vordering te weten immateriële schadevergoeding € 250,-- en materiële schadevergoeding van € 7,78 vermeerderd met de wettelijke rente vanaf 23 mei 2015 tot aan de dag der algehele voldoening.',
  'Eis officier van justitie',
  'Geding in cassatie',
  'Geschil',
  'Geschil in hoger beroep',
  'Geschil, alsmede standpunten en conclusies van partijen',
  'Geschil11. In geschil is de hoogte van de verschuldigde overdrachtsbelasting. Meer specifiek is in geschil of de artikelen 7 en 12 van de Wet BRV, dan wel de zogenoemde ‘doorkijkarresten’ van de Hoge Raad van 23 februari 2007 (nr. 41591, ECLI:NL:HR2007:AU8559) en van 10 juni 2011 (nr. 10/00498, ECLI:NL:HR:2011:BQ7580) toepassing vinden.',
  'Het geding in cassatie',
  'Het geschil',
  'Het geschil in hoger beroep',
  'Het geschil, de standpunten en conclusies van partijen',
  'Het standpunt van [A]',
  'Het standpunt van de officier van justitie.De officier van justitie acht het onder feit 1 primair, feit 2 en feit 3 ten laste gelegde wettig en overtuigend bewezen.',
  'Het verweer',
  'Het verweer in reconventie',
  'Het verzoek',
  'Het verzoek om aanhouding.',
  'Omschrijving geschil in hoger beroep en conclusies van partijen',
  'Omschrijving geschil na verwijzing en conclusies van partijen',
  'Standpunt van de man',
  'Standpunt van de vrouw',
  'Tenlastelegging',
  'Vordering benadeelde partij en schadevergoedingsmaatregel',
  'Vordering officier van justitie',
  'Vordering tenuitvoerlegging',
  'Vordering tot tenuitvoerlegging',
  'Vordering van de benadeelde partij [benadeelde partij 1]',
  'Vordering van de benadeelde partij [benadeelde partij 2]',
  'Vordering van de benadeelde partij [benadeelde partij 3]',
  'Vordering van de benadeelde partij [benadeelde partij 4]',
  'Vordering van de benadeelde partij [benadeelde partij 5]',
  'Vordering van de benadeelde partij [benadeelde partij]',
  'Vordering van de benadeelde partij [benadeelde]',
  'Vordering van het openbaar ministerie']}

In [14]:
df_final = df_filtered_cascade.copy()
df_final['data']=df_final['extracted_data'].apply(lambda d: ''.join(list(d.values())) if isinstance(d, dict) else None)
df_final

,case_name,extracted_data,matched_headers,matched_groups,matched_norm_titles,match_methods,number_of_headers,data
0,ECLI:NL:GHAMS:2015:2960.txt,{'Feiten': 'De kantonrechter heeft in het best...,"[Feiten, Beoordeling, Beslissing]","[Feiten, Beoordeling, Beslissing]","[feiten, beoordeling, beslissing]","[exact, exact, exact]",3,De kantonrechter heeft in het bestreden vonnis...
1,ECLI:NL:GHAMS:2015:5282.txt,{'De gronden van de beslissing': 'Nu van de zi...,"[De gronden van de beslissing, De beslissing]","[Beoordeling, Beslissing]","[de gronden van de beslissing, de beslissing]","[exact, exact]",2,Nu van de zijde van de partijen geen bezwaren ...
2,ECLI:NL:GHARL:2016:7748.txt,{'De verdere motivering van de beslissing in h...,[De verdere motivering van de beslissing in ho...,"[Beoordeling, Beslissing]",[de verdere motivering van de beslissing in ho...,"[token_overlap, exact]",2,2.1 Bij voormeld tussenarrest heeft het hof pa...
3,ECLI:NL:GHDHA:2016:706.txt,{'Inhoudelijke beoordeling': '45. Op 1 januari...,"[Inhoudelijke beoordeling, Inhoudelijke beoord...","[Beoordeling, Beoordeling, Beoordeling, Beoord...","[inhoudelijke beoordeling, inhoudelijke beoord...","[fuzzy, fuzzy, fuzzy, fuzzy, fuzzy, fuzzy, fuzzy]",7,45. Op 1 januari 2002 is een nieuw Turks Burge...
4,ECLI:NL:GHSHE:2021:1091.txt,{'De beoordeling': '2.1. De Hoge Raad heeft in...,"[De beoordeling, De uitspraak]","[Beoordeling, Beslissing]","[de beoordeling, de uitspraak]","[exact, exact]",2,2.1. De Hoge Raad heeft in zijn voornoemde arr...
...,...,...,...,...,...,...,...,...
95,ECLI:NL:RBNNE:2018:4847.txt,{'Overwegingen': '1. De rechtbank gaat uit van...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,1. De rechtbank gaat uit van de volgende relev...
96,ECLI:NL:RBOBR:2019:10.txt,{'Overwegingen': 'De aanleiding voor deze proc...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,De aanleiding voor deze procedure 1. Eiser wil...
97,ECLI:NL:RBOVE:2019:1349.txt,{'Overwegingen': '1.Op 15 oktober 2017 heeft e...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,1.Op 15 oktober 2017 heeft eiser verweerder ve...
98,ECLI:NL:RBROT:2016:4797.txt,{'Overwegingen': '1. Verweerder heeft aan het ...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,1. Verweerder heeft aan het bestreden besluit ...
99,ECLI:NL:RBZWB:2015:638.txt,{'Overwegingen': '1. Op grond van de stukken e...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,1.\tOp grond van de stukken en de behandeling ...

In [15]:
df_final.data[0]

'De kantonrechter heeft in het bestreden vonnis onder het kopje “De feiten” de feiten vastgesteld die zij tot uitgangspunt heeft genomen. Deze feiten zijn in hoger beroep niet in geschil en dienen derhalve ook het hof als uitgangspunt.3.1. Op 10 oktober 2012 heeft [geïntimeerde] een bedrag van € 15.000,- ter leen verstrekt aan [appellante] in verband met het voornemen van [appellante] een onderneming (verkoop van voedingssupplementen) te beginnen. Op 4/5 januari 2013 heeft [appellante] een schriftelijke verklaring opgesteld, die beide partijen hebben ondertekend. Deze verklaring houdt onder meer in: “Dit bedrag wordt in gedeelten terugbetaald; wanneer er door deze promotie, inschrijvingen en verdiensten in welke vorm dan ook; ontvangen worden; gaat daar zo snel mogelijk het grootste deel direct van terug/retour naar de rekening van dhr. [geïntimeerde] (…) Zoals afgesproken; zo ook: zou er een grote doos met voedingssupplementen ter waarde van € 2.000,= bij dhr. v. Diest terecht komen voor eigen gebruik (…) dit bedrag zou van de lening afgetrokken kunnen + mogen worden, maar nu eind 2012; laatste week; komt dhr. hiervan op zijn schrede terug”. 3.2. [geïntimeerde] vorderde in eerste aanleg (samengevat) nietigverklaring van de tussen partijen gesloten overeenkomst en veroordeling van [appellante] tot betaling van € 15.000,-. In voorwaardelijke reconventie vorderde [appellante] veroordeling van [geïntimeerde] tot betaling van € 6.530,50, te vermeerderen met wettelijke rente. 3.3. De kantonrechter heeft het beroep van [geïntimeerde] op nietigheid van de overeenkomst afgewezen. Zij heeft [appellante] op de voet van artikel 7A:1798 BW veroordeeld tot terugbetaling van de van [geïntimeerde] geleende € 15.000,- in vijf maandelijkse termijnen van € 3.000,- waarvan de eerste vervalt op 1 februari 2014. De kantonrechter heeft de voorwaardelijke vordering in reconventie  - gegrond op de stelling van [appellante] dat [geïntimeerde] voedingssupplementen ten bedrage van € 6.530,50 van haar had gekocht – afgewezen. Zowel in conventie als in reconventie is [appellante] in de proceskosten veroordeeld. De kantonrechter heeft bij vonnis van 13 maart 2014 overwogen dat de beslissing in conventie ten onrechte uitvoerbaar bij voorraad was verklaard en het vonnis van 16 januari 2014 in die zin verbeterd. 3.4. Tegen de beslissingen in het vonnis van 16 januari 2014 komt [appellante] op in hoger beroep. 3.5. Het hof zal eerst grief 2 bespreken. Daarin klaagt [appellante] dat de kantonrechter niet heeft aangenomen dat [geïntimeerde] een doos met voedingssupplementen heeft besteld en afgenomen van haar. Deze grief slaagt. Het staat vast dat [appellante] een doos met voedingssupplementen heeft achtergelaten bij [geïntimeerde] en dat [geïntimeerde] deze op dat moment heeft behouden en in elk geval een aantal van deze voedingssupplementen heeft gebruikt. De lezing van [appellante] dat de waarde van de doos met voedingssupplementen - naar in hoger beroep niet meer in geschil is: € 2.000,- - zou mogen worden afgetrokken van het geleende bedrag van € 15.000,- vindt bovendien steun in de eerdergenoemde brief van [appellante] , die ook door [geïntimeerde] is ondertekend. In het licht van dit een en ander acht het hof de bestrijding door [geïntimeerde] van de lezing van [appellante] onvoldoende gemotiveerd. Het beroep op verrekening slaagt daarom, zodat de terugbetalingsverplichting van [appellante] nog een bedrag van € 13.000,- beloopt. 3.6. Grief 1 strekt ertoe dat het hof de terugbetalingstermijnen opnieuw zal vaststellen en daarbij rekening zal houden met de draagkracht van [appellante] . [appellante] wijst erop dat [geïntimeerde] op de hoogte was van haar financiële positie, wist waar [appellante] het geld voor zou gaan gebruiken en dat er dus een risico bestond dat zij geen omzet/winst zou maken. Zij brengt naar voren dat zij enkel inkomsten heeft uit haar AOW-uitkering van ongeveer € 950,- per maand en dat zij in termijnen van € 50,- zou kunnen terugbetalen. Executoriale verkoop van haar woning zou in de gegeven omstandigheden misbruik van executiebevoegdheid opleveren. Het hof oordeelt als volgt. 3.7. Uit de overeenkomst tussen partijen volgt dat [appellante] het geleende bedrag zal terugbetalen wanneer zij daartoe in staat zal zijn. Ingevolge artikel 7A:1798 BW dient de rechter in zodanig geval de tijd der teruggave te bepalen “naar gelang der omstandigheden”. Op basis van de wederzijdse stellingen van partijen kan worden aangenomen dat [appellante] geen inkomsten meer zal ontvangen uit haar onderneming. Van [appellante] had verwacht mogen worden dat zij ook inzicht zou geven in haar vermogenspositie. Uit haar eigen stellingen volgt dat zij eigenaar is van een woning. Iedere verdere bijzonderheid te dien aanzien – bijvoorbeeld de waarde van die woning, eventuele hypothecaire schuld, eventuele financieringsmogelijkheden in verband met een en ander – is echter achterwege gebleven. Bij gebreke van toereikende gegevens aan de zijde van [appellante] bestaat onvoldoende aanknopingspunt om tot een andere betalingswijze van het resterende bedrag van € 13.000,- te besluiten, zodat grief 1 faalt. 3.8. In grief 3 betoogt [appellante] dat de kantonrechter haar ten onrechte heeft veroordeeld in de proceskosten, zowel in conventie als in voorwaardelijke reconventie. 3.9. Deze grief faalt. Terugbetaling van het geleende bedrag was de inzet van het geding in eerste aanleg in conventie. Het verweer daartegen van [appellante] is verworpen. De omstandigheid dat de uitkomst is dat niet € 15.000,- maar € 13.000,- dient te worden terugbetaald en dat terugbetaling mogelijk is in een aantal termijnen, neemt niet weg dat [appellante] als de overwegend in het ongelijk gestelde partij moet worden aangemerkt. Dat geldt ook ten aanzien van de voorwaardelijk ingestelde vordering in reconventie nu [appellante] in eerste aanleg nog een bedrag vorderde van € 6.530,50 en zich niet heeft beperkt tot het bedrag van € 2.000,- dat volgens haar eigen stellingen in hoger beroep tussen partijen was afgesproken. 3.10. Het bestreden vonnis zal worden vernietigd, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan € 13.000,-. Het hof zal in zoverre opnieuw recht doen. 3.11. [appellante] zal als de overwegend in het ongelijk gestelde partij worden veroordeeld in de kosten van het hoger beroep.Het hof: vernietigt het vonnis waarvan beroep, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan € 13.000,-; in zoverre opnieuw rechtdoende: veroordeelt [appellante] tot betaling aan [geïntimeerde] van een bedrag van € 13.000,-, bepaalt dat voor “vijf maandelijkse termijnen van € 3.000,00” gelezen moet worden: vier maandelijkse termijnen van € 3.000,- en één termijn van € 1.000,- en wijst het meer gevorderde af; bekrachtigt het vonnis voor het overige; veroordeelt [appellante] in de kosten van het geding in hoger beroep, tot op heden aan de zijde van [geïntimeerde] begroot op € 704,- aan verschotten en € 894,- voor salaris; verklaart dit arrest uitvoerbaar bij voorraad. Dit arrest is gewezen door mrs. J.E. Molenaar, C.M. Aarts en R.J.F. Thiessen en door de rolraadsheer in het openbaar uitgesproken op 14 juli 2015.'

In [16]:
import re

def replace_money(text):
    if pd.isna(text):
        return text
    text = str(text)
    # covers € / eur / euro followed by numbers, commas, dots, or spaces
    text = re.sub(r"(€|eur|euro)\s?[\d\.\,]+", "[geld]", text, flags=re.IGNORECASE)
    return text

def replace_dates_by_month_window(text):
    if pd.isna(text):
        return text
    text = str(text)
    months = [
        "januari","februari","maart","april","mei","juni","juli",
        "augustus","september","oktober","november","december",
        "jan","feb","mrt","apr","jun","jul","aug","sep","okt","nov","dec"
    ]
    pattern = r"(?:\b\S+\s)?\b(" + "|".join(months) + r")\b(?:\s\S+)?"
    text = re.sub(pattern, "[datum]", text, flags=re.IGNORECASE)
    return text

import re
import pandas as pd

# Compile once for speed
PARTICLES = r"(?:van|de|den|der|het|ten|ter|te|la|le|l'|d')"
SURNAME = r"[A-Z][A-Za-zÀ-ÖØ-öø-ÿ\-']+"
INITIALS_DOTTED = r"(?:[A-Z]\.\s*){1,5}"
HONORIFICS = r"(?:mr|mrs|mevr|mw|meneer|dr|drs|prof|prof\.dr)\.?"

# 1) Honorific + initials + surname  (e.g., "mr. P. Oudkerk", "MR A.B. de Vries")
pat_honorific_initials = re.compile(
    rf"\b{HONORIFICS}\s+{INITIALS_DOTTED}(?:{PARTICLES}\s+)?{SURNAME}\b",
    flags=re.IGNORECASE
)

# 2) Initials + surname (no honorific)  (e.g., "J.E. Molenaar", "C.M. Aarts")
pat_initials_surname = re.compile(
    rf"\b{INITIALS_DOTTED}(?:{PARTICLES}\s+)?{SURNAME}\b"
)

# 3) Optional broader form: Firstname + surname (riskier — leave OFF by default)
#    e.g., "Jan de Vries" | enable by setting BROAD_FIRSTNAME=True
BROAD_FIRSTNAME = False
pat_firstname_surname = re.compile(
    rf"\b[A-Z][a-zà-öø-ÿ]{{2,}}\s+(?:{PARTICLES}\s+)?{SURNAME}\b"
)

def replace_person_names(text, broad_firstname=BROAD_FIRSTNAME):
    if pd.isna(text): 
        return text
    s = str(text)

    # Protect placeholders like [appellante], [geïntimeerde], [datum], [geld]
    protected = {}
    def _protect(m):
        key = f"§§§{len(protected)}§§§"
        protected[key] = m.group(0)
        return key
    s = re.sub(r"\[[^\]\n]{1,50}\]", _protect, s)

    s = pat_honorific_initials.sub("[naam]", s)
    s = pat_initials_surname.sub("[naam]", s)
    if broad_firstname:
        s = pat_firstname_surname.sub("[naam]", s)

    # Restore placeholders
    for k, v in protected.items():
        s = s.replace(k, v)
    return s

# EXAMPLE: apply to your dataframe
# df = pd.read_csv("your_dataset.csv")

# print(df[["data_clean"]].head(10))





df_final["data_clean"] = df_final["data"].apply(replace_money)
df_final["data_clean"] = df_final["data_clean"].apply(replace_dates_by_month_window)
df_final["data_clean"] = df_final["data_clean"].astype(str).map(replace_person_names)

#df_final["data_clean"] = df_final["data_clean"].apply(replace_dates)
df_final.data_clean[0]

'De kantonrechter heeft in het bestreden vonnis onder het kopje “De feiten” de feiten vastgesteld die zij tot uitgangspunt heeft genomen. Deze feiten zijn in hoger beroep niet in geschil en dienen derhalve ook het hof als uitgangspunt.3.1. Op [datum] heeft [geïntimeerde] een bedrag van [geld]- ter leen verstrekt aan [appellante] in verband met het voornemen van [appellante] een onderneming (verkoop van voedingssupplementen) te beginnen. Op [datum] heeft [appellante] een schriftelijke verklaring opgesteld, die beide partijen hebben ondertekend. Deze verklaring houdt onder meer in: “Dit bedrag wordt in gedeelten terugbetaald; wanneer er door deze promotie, inschrijvingen en verdiensten in welke vorm dan ook; ontvangen worden; gaat daar zo snel mogelijk het grootste deel direct van terug/retour naar de rekening van dhr. [geïntimeerde] (…) Zoals afgesproken; zo ook: zou er een grote doos met voedingssupplementen ter waarde van [geld]= bij dhr. v. Diest terecht komen voor eigen gebruik (…) dit bedrag zou van de lening afgetrokken kunnen + mogen worden, maar nu eind 2012; laatste week; komt dhr. hiervan op zijn schrede terug”. 3.2. [geïntimeerde] vorderde in eerste aanleg (samengevat) nietigverklaring van de tussen partijen gesloten overeenkomst en veroordeling van [appellante] tot betaling van [geld]-. In voorwaardelijke reconventie vorderde [appellante] veroordeling van [geïntimeerde] tot betaling van [geld] te vermeerderen met wettelijke rente. 3.3. De kantonrechter heeft het beroep van [geïntimeerde] op nietigheid van de overeenkomst afgewezen. Zij heeft [appellante] op de voet van artikel 7A:1798 BW veroordeeld tot terugbetaling van de van [geïntimeerde] geleende [geld]- in vijf maandelijkse termijnen van [geld]- waarvan de eerste vervalt op [datum] De kantonrechter heeft de voorwaardelijke vordering in reconventie  - gegrond op de stelling van [appellante] dat [geïntimeerde] voedingssupplementen ten bedrage van [geld] van haar had gekocht – afgewezen. Zowel in conventie als in reconventie is [appellante] in de proceskosten veroordeeld. De kantonrechter heeft bij vonnis van [datum] overwogen dat de beslissing in conventie ten onrechte uitvoerbaar bij voorraad was verklaard en het vonnis van [datum] in die zin verbeterd. 3.4. Tegen de beslissingen in het vonnis van [datum] komt [appellante] op in hoger beroep. 3.5. Het hof zal eerst grief 2 bespreken. Daarin klaagt [appellante] dat de kantonrechter niet heeft aangenomen dat [geïntimeerde] een doos met voedingssupplementen heeft besteld en afgenomen van haar. Deze grief slaagt. Het staat vast dat [appellante] een doos met voedingssupplementen heeft achtergelaten bij [geïntimeerde] en dat [geïntimeerde] deze op dat moment heeft behouden en in elk geval een aantal van deze voedingssupplementen heeft gebruikt. De lezing van [appellante] dat de waarde van de doos met voedingssupplementen - naar in hoger beroep niet meer in geschil is: [geld]- - zou mogen worden afgetrokken van het geleende bedrag van [geld]- vindt bovendien steun in de eerdergenoemde brief van [appellante] , die ook door [geïntimeerde] is ondertekend. In het licht van dit een en ander acht het hof de bestrijding door [geïntimeerde] van de lezing van [appellante] onvoldoende gemotiveerd. Het beroep op verrekening slaagt daarom, zodat de terugbetalingsverplichting van [appellante] nog een bedrag van [geld]- beloopt. 3.6. Grief 1 strekt ertoe dat het hof de terugbetalingstermijnen opnieuw zal vaststellen en daarbij rekening zal houden met de draagkracht van [appellante] . [appellante] wijst erop dat [geïntimeerde] op de hoogte was van haar financiële positie, wist waar [appellante] het geld voor zou gaan gebruiken en dat er dus een risico bestond dat zij geen omzet/winst zou maken. Zij brengt naar voren dat zij enkel inkomsten heeft uit haar AOW-uitkering van ongeveer [geld]- per maand en dat zij in termijnen van [geld]- zou kunnen terugbetalen. Executoriale verkoop van haar woning zou in de gegeven omstandigheden misbruik van executiebevoegdheid opleveren. Het hof oordeelt als volgt. 3.7. Uit de overeenkomst tussen partijen volgt dat [appellante] het geleende bedrag zal terugbetalen wanneer zij daartoe in staat zal zijn. Ingevolge artikel 7A:1798 BW dient de rechter in zodanig geval de tijd der teruggave te bepalen “naar gelang der omstandigheden”. Op basis van de wederzijdse stellingen van partijen kan worden aangenomen dat [appellante] geen inkomsten meer zal ontvangen uit haar onderneming. Van [appellante] had verwacht mogen worden dat zij ook inzicht zou geven in haar vermogenspositie. Uit haar eigen stellingen volgt dat zij eigenaar is van een woning. Iedere verdere bijzonderheid te dien aanzien – bijvoorbeeld de waarde van die woning, eventuele hypothecaire schuld, eventuele financieringsmogelijkheden in verband met een en ander – is echter achterwege gebleven. Bij gebreke van toereikende gegevens aan de zijde van [appellante] bestaat onvoldoende aanknopingspunt om tot een andere betalingswijze van het resterende bedrag van [geld]- te besluiten, zodat grief 1 faalt. 3.8. In grief 3 betoogt [appellante] dat de kantonrechter haar ten onrechte heeft veroordeeld in de proceskosten, zowel in conventie als in voorwaardelijke reconventie. 3.9. Deze grief faalt. Terugbetaling van het geleende bedrag was de inzet van het geding in eerste aanleg in conventie. Het verweer daartegen van [appellante] is verworpen. De omstandigheid dat de uitkomst is dat niet [geld]- maar [geld]- dient te worden terugbetaald en dat terugbetaling mogelijk is in een aantal termijnen, neemt niet weg dat [appellante] als de overwegend in het ongelijk gestelde partij moet worden aangemerkt. Dat geldt ook ten aanzien van de voorwaardelijk ingestelde vordering in reconventie nu [appellante] in eerste aanleg nog een bedrag vorderde van [geld] en zich niet heeft beperkt tot het bedrag van [geld]- dat volgens haar eigen stellingen in hoger beroep tussen partijen was afgesproken. 3.10. Het bestreden vonnis zal worden vernietigd, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan [geld]-. Het hof zal in zoverre opnieuw recht doen. 3.11. [appellante] zal als de overwegend in het ongelijk gestelde partij worden veroordeeld in de kosten van het hoger beroep.Het hof: vernietigt het vonnis waarvan beroep, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan [geld]-; in zoverre opnieuw rechtdoende: veroordeelt [appellante] tot betaling aan [geïntimeerde] van een bedrag van [geld]-, bepaalt dat voor “vijf maandelijkse termijnen van [geld]” gelezen moet worden: vier maandelijkse termijnen van [geld]- en één termijn van [geld]- en wijst het meer gevorderde af; bekrachtigt het vonnis voor het overige; veroordeelt [appellante] in de kosten van het geding in hoger beroep, tot op heden aan de zijde van [geïntimeerde] begroot op [geld]- aan verschotten en [geld]- voor salaris; verklaart dit arrest uitvoerbaar bij voorraad. Dit arrest is gewezen door [naam], [naam] en [naam] en door de rolraadsheer in het openbaar uitgesproken op [datum]'

## Sentence Splitter

In [17]:
### Split the text data into sentences ###
from sentence_splitter import sentence_splitter
ss = sentence_splitter()


df = df_final[['case_name','data_clean']].rename(columns={"data_clean":"text"})
df['label'] = ["None" for _ in range(len(df))]
text_col = "text"  #
# keep everything else as metadata
meta_cols = ["case_name"]
xml_data = ss.dataframe_to_sentences(df, text_col="text", label_col="label", meta_cols=meta_cols)
#xml_data.to_csv(r"final/annotations_sentences_clean_v4.csv", index=False)
xml_data.head()

,block_row,sent_index,sent_text,sent_len,label,case_name
0,1,1,De kantonrechter heeft in het bestreden vonnis...,136,None,ECLI:NL:GHAMS:2015:2960.txt
1,1,2,Deze feiten zijn in hoger beroep niet in gesch...,97,None,ECLI:NL:GHAMS:2015:2960.txt
2,1,3,Op [datum] heeft [geïntimeerde] een bedrag van...,200,None,ECLI:NL:GHAMS:2015:2960.txt
3,1,4,Op [datum] heeft [appellante] een schriftelijk...,106,None,ECLI:NL:GHAMS:2015:2960.txt
4,1,5,Deze verklaring houdt onder meer in: “Dit bedr...,278,None,ECLI:NL:GHAMS:2015:2960.txt

In [18]:
### Print sentences with labels ###
for ele, label in zip(xml_data.sent_text,xml_data.label):
    print(ele + "====>[" + str(label) + "]")
    print("#####")

De kantonrechter heeft in het bestreden vonnis onder het kopje “De feiten” de feiten vastgesteld die zij tot uitgangspunt heeft genomen.====>[None]
#####
Deze feiten zijn in hoger beroep niet in geschil en dienen derhalve ook het hof als uitgangspunt.====>[None]
#####
Op [datum] heeft [geïntimeerde] een bedrag van [geld]- ter leen verstrekt aan [appellante] in verband met het voornemen van [appellante] een onderneming (verkoop van voedingssupplementen) te beginnen.====>[None]
#####
Op [datum] heeft [appellante] een schriftelijke verklaring opgesteld, die beide partijen hebben onderteken====>[None]
#####
Deze verklaring houdt onder meer in: “Dit bedrag wordt in gedeelten terugbetaald; wanneer er door deze promotie, inschrijvingen en verdiensten in welke vorm dan ook; ontvangen worden; gaat daar zo snel mogelijk het grootste deel direct van terug/retour naar de rekening van dhr.====>[None]
#####
[geïntimeerde] (...) Zoals afgesproken; zo ook: zou er een grote doos met voedingssupplementen ter waarde van [geld]= bij dhr.====>[None]
#####
Diest terecht komen voor eigen gebruik (...) dit bedrag zou van de lening afgetrokken kunnen + mogen worden, maar nu eind 2012; laatste week; komt dhr. hiervan op zijn schrede terug”.====>[None]
#####
[geïntimeerde] vorderde in eerste aanleg (samengevat) nietigverklaring van de tussen partijen gesloten overeenkomst en veroordeling van [appellante] tot betaling van [geld]-.====>[None]
#####
In voorwaardelijke reconventie vorderde [appellante] veroordeling van [geïntimeerde] tot betaling van [geld] te vermeerderen met wettelijke rente.====>[None]
#####
De kantonrechter heeft het beroep van [geïntimeerde] op nietigheid van de overeenkomst afgewezen.====>[None]
#####
Zij heeft [appellante] op de voet van artikel 7A:1798 BW veroordeeld tot terugbetaling van de van [geïntimeerde] geleende [geld]- in vijf maandelijkse termijnen van [geld]- waarvan de eerste vervalt op [datum] De kantonrechter heeft de voorwaardelijke vordering in reconventie - gegrond op de stelling van [appellante] dat [geïntimeerde] voedingssupplementen ten bedrage van [geld] van haar had gekocht – afgewezen.====>[None]
#####
Zowel in conventie als in reconventie is [appellante] in de proceskosten veroordee====>[None]
#####
De kantonrechter heeft bij vonnis van [datum] overwogen dat de beslissing in conventie ten onrechte uitvoerbaar bij voorraad was verklaard en het vonnis van [datum] in die zin verbeter====>[None]
#####
Tegen de beslissingen in het vonnis van [datum] komt [appellante] op in hoger beroep.====>[None]
#####
Het hof zal eerst grief 2 bespreken.====>[None]
#####
Daarin klaagt [appellante] dat de kantonrechter niet heeft aangenomen dat [geïntimeerde] een doos met voedingssupplementen heeft besteld en afgenomen van haar.====>[None]
#####
Deze grief slaagt.====>[None]
#####
Het staat vast dat [appellante] een doos met voedingssupplementen heeft achtergelaten bij [geïntimeerde] en dat [geïntimeerde] deze op dat moment heeft behouden en in elk geval een aantal van deze voedingssupplementen heeft gebruikt.====>[None]
#####
De lezing van [appellante] dat de waarde van de doos met voedingssupplementen - naar in hoger beroep niet meer in geschil is: [geld]- - zou mogen worden afgetrokken van het geleende bedrag van [geld]- vindt bovendien steun in de eerdergenoemde brief van [appellante], die ook door [geïntimeerde] is onderteken====>[None]
#####
In het licht van dit een en ander acht het hof de bestrijding door [geïntimeerde] van de lezing van [appellante] onvoldoende gemotiveer====>[None]
#####
Het beroep op verrekening slaagt daarom, zodat de terugbetalingsverplichting van [appellante] nog een bedrag van [geld]- beloopt.====>[None]
#####
Grief 1 strekt ertoe dat het hof de terugbetalingstermijnen opnieuw zal vaststellen en daarbij rekening zal houden met de draagkracht van [appellante].====>[None]
#####
[appellante] wijst erop dat [geïntimeerde] op de hoogte was van haar financiële positie, wist waar [appellante] het geld voor zou gaan gebruiken en dat er dus een risico bestond dat zij geen omzet/winst zou maken.====>[None]
#####
Zij brengt naar voren dat zij enkel inkomsten heeft uit haar AOW-uitkering van ongeveer [geld]- per maand en dat zij in termijnen van [geld]- zou kunnen terugbetalen.====>[None]
#####
Executoriale verkoop van haar woning zou in de gegeven omstandigheden misbruik van executiebevoegdheid opleveren.====>[None]
#####
Het hof oordeelt als volgt.====>[None]
#####
Uit de overeenkomst tussen partijen volgt dat [appellante] het geleende bedrag zal terugbetalen wanneer zij daartoe in staat zal zijn.====>[None]
#####
Ingevolge artikel 7A:1798 BW dient de rechter in zodanig geval de tijd der teruggave te bepalen “naar gelang der omstandigheden”.====>[None]
#####
Op basis van de wederzijdse stellingen van partijen kan worden aangenomen dat [appellante] geen inkomsten meer zal ontvangen uit haar onderneming.====>[None]
#####
Van [appellante] had verwacht mogen worden dat zij ook inzicht zou geven in haar vermogenspositie.====>[None]
#####
Uit haar eigen stellingen volgt dat zij eigenaar is van een woning.====>[None]
#####
Iedere verdere bijzonderheid te dien aanzien – bijvoorbeeld de waarde van die woning, eventuele hypothecaire schuld, eventuele financieringsmogelijkheden in verband met een en ander – is echter achterwege gebleven.====>[None]
#####
Bij gebreke van toereikende gegevens aan de zijde van [appellante] bestaat onvoldoende aanknopingspunt om tot een andere betalingswijze van het resterende bedrag van [geld]- te besluiten, zodat grief 1 faalt.====>[None]
#####
In grief 3 betoogt [appellante] dat de kantonrechter haar ten onrechte heeft veroordeeld in de proceskosten, zowel in conventie als in voorwaardelijke reconventie.====>[None]
#####
Deze grief faalt.====>[None]
#####
Terugbetaling van het geleende bedrag was de inzet van het geding in eerste aanleg in conventie.====>[None]
#####
Het verweer daartegen van [appellante] is verworpen.====>[None]
#####
De omstandigheid dat de uitkomst is dat niet [geld]- maar [geld]- dient te worden terugbetaald en dat terugbetaling mogelijk is in een aantal termijnen, neemt niet weg dat [appellante] als de overwegend in het ongelijk gestelde partij moet worden aangemerkt.====>[None]
#####
Dat geldt ook ten aanzien van de voorwaardelijk ingestelde vordering in reconventie nu [appellante] in eerste aanleg nog een bedrag vorderde van [geld] en zich niet heeft beperkt tot het bedrag van [geld]- dat volgens haar eigen stellingen in hoger beroep tussen partijen was afgesproken.====>[None]
#####
Het bestreden vonnis zal worden vernietigd, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan [geld]-.====>[None]
#####
Het hof zal in zoverre opnieuw recht doen.====>[None]
#####
[appellante] zal als de overwegend in het ongelijk gestelde partij worden veroordeeld in de kosten van het hoger beroep.====>[None]
#####
Het hof: vernietigt het vonnis waarvan beroep, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan [geld]-; in zoverre opnieuw rechtdoende: veroordeelt [appellante] tot betaling aan [geïntimeerde] van een bedrag van [geld]-, bepaalt dat voor “vijf maandelijkse termijnen van [geld]” gelezen moet worden: vier maandelijkse termijnen van [geld]- en één termijn van [geld]- en wijst het meer gevorderde af; bekrachtigt het vonnis voor het overige; veroordeelt [appellante] in de kosten van het geding in hoger beroep, tot op heden aan de zijde van [geïntimeerde] begroot op [geld]- aan verschotten en [geld]- voor salaris; verklaart dit arrest uitvoerbaar bij voorraa====>[None]
#####
Dit arrest is gewezen door [naam], [naam] en [naam] en door de rolraadsheer in het openbaar uitgesproken op [datum]====>[None]
#####
Nu van de zijde van de partijen geen bezwaren zijn vernomen tegen de beëindiging van het bevolen onderzoek en de getroffen onmiddellijke voorziening en de Ondernemingskamer het aannemelijk acht dat, naar de huidige stand van zaken, onvoldoende financiële basis bestaat om het onderzoek een aanvang te laten nemen, zal de Ondernemingskamer het bevolen onderzoek en de getroffen onmiddellijke voorziening beëindigen en wel per heden.====>[None]
#####
De Ondernemingskamer: beëindigt met ingang van heden het bij haar beschikking van [datum] bevolen onderzoek naar het beleid en de gang van zaken van ABP Dynamics B.====>[None]
#####
; beëindigt met ingang van heden de bij haar beschikking van [datum] getroffen onmiddellijke voorziening; verklaart deze beschikking uitvoerbaar bij voorraa====>[None]
#####
Deze beschikking is gegeven door [naam], voorzitter, [naam] Weme en [naam] thoe Slooten, raadsheren, en [naam] en [naam], raden, in tegenwoordigheid van [naam], griffier, en uitgesproken ter openbare terechtzitting van de Ondernemingskamer van [datum]====>[None]
#####
Bij voormeld tussenarrest heeft het hof partijen in de gelegenheid gesteld zich uit te laten over de vraag of de overeenkomst (mede) gekwalificeerd dient te worden als pacht en of in dat geval verwijzing naar de pachtkamer dient te volgen. 2.2 [appellant] heeft bij akte na tussenarrest kort weergegeven aangevoerd dat met name blijkens de afspraken omtrent investeringen en delen van de winst geen sprake is van zuivere pacht maar van een samenwerking op zoveel mogelijk gelijke basis, waarbij beiden zeggenschap hadden omtrent de (wijze van) samenwerking, zijnde de bessenteelt, en dat het hof is gebonden aan het bevoegdheidsoordeel van de rechtbank.====>[None]
#####
Ter onderbouwing van zijn stelling dat er geen sprake is van zuivere pacht verwijst [appellant] naar een (als productie 13 overgelegd) e-mailbericht van [datum] [geïntimeerde] heeft bij akte na tussenarrest in de kern aangevoerd dat de rechtsverhouding tussen partijen niet als pacht kwalificeert omdat beide partijen ondernemersrisico lopen en dat de goede procesorde zich verzet tegen verwijzing naar de pachtkamer.====>[None]
#####
Ook volgens [geïntimeerde] is het hof gebonden aan het impliciete bevoegdheidsoordeel van de rechtbank. 2.3 Naar het oordeel van het hof dient de tussen partijen bestaande rechtsverhouding niettemin (mede) te worden gekwalificeerd als pacht.====>[None]
#####
Hetgeen [appellant] met verwijzing naar de als productie 13 overgelegde e-mail van [persoon 1] (hierna: [persoon 1] ) van [datum] heeft aangevoerd doet niet af aan hetgeen het hof in rechtsoverweging 3.3 van voormeld tussenarrest heeft overwogen omtrent de considerans en de inhoud van de overeenkomst van samenwerking.====>[None]
#####
Daaruit blijkt dat [appellant] zich jegens [geïntimeerde] heeft verbonden tegen voldoening van een vergoeding een perceel grond ter beschikking te stellen ten behoeve van de bedrijfsmatige uitoefening van de landbouw, meer specifiek de fruitteelt, als bedoeld in artikel 7:311 in verbinding met artikel 7:312 BW.====>[None]
#####
[appellant] heeft voorts met genoemde e-mail van [persoon 1] onvoldoende onderbouwd weersproken dat [geïntimeerde] in de aanvangsfase het overgrote deel van de werkzaamheden en daarna alle werkzaamheden naar eigen inzicht heeft (laten) verricht(en).====>[None]
#####
[geïntimeerde] heeft zich hierover in zijn akte niet uitgelaten.====>[None]
#####
Dat [appellant] de investeringen voor zijn rekening zou nemen en dat beide partijen ondernemersrisico lopen in de zin dat beide partijen voor 50% delen in winst en verlies, maakt gelet op het voorgaande niet dat de rechtsverhouding tussen partijen niet als pacht dient te worden gekwalificeer====>[None]
#####
Hetgeen partijen daaromtrent ( [appellant] bij akte na tussenarrest, sub 3 en [geïntimeerde] bij akte na tussenarrest, sub I) hebben aangevoerd is onvoldoende voor een andersluidend oordeel. 2.4 Hetgeen [appellant] met verwijzing naar genoemde e-mail van [persoon 1] heeft aangevoerd doet evenmin af aan hetgeen het hof in rechtsoverweging 3.4 heeft overwogen omtrent het document “Bessen overzicht verdeling kosten/baten”, de e-mail van [datum] het document “saldo berekeningen toekomstige samenwerking” en de e-mail van [datum] Daarin wordt immers steeds met zoveel woorden gesproken van pacht. 2.5 Gelet hierop dient de gewone rechter zich onbevoegd te verklaren en dient de zaak ter verdere behandeling en beoordeling te worden verwezen naar de pachtkamer van dit hof (vgl. HR [datum] ECLI:NL:HR:2006:A====>[None]
#####
Van strijd met de eisen van de goede procesorde is geen sprake.====>[None]
#####
Dat de zaak vanwege de materiële aspecten van het geschil wordt behandeld door de bij uitstek daartoe geëquipeerde pachtrechter acht het hof van essentieel belang.====>[None]
#####
Dit belang weegt zwaarder dan de omstandigheid dat partijen door verwijzing een instantie zou worden onthouden omdat zij zich hieromtrent in eerste aanleg niet hebben uitgelaten.====>[None]
#####
Het hof, recht doende in hoger beroep: verwijst de zaak naar de pachtkamer van dit hof. Dit arrest is gewezen door [naam], [naam] en [naam] en is in tegenwoordigheid van de griffier in het openbaar uitgesproken op [datum]====>[None]
#####
Op [datum] is een nieuw Turks Burgerlijk Wetboek (Turks BW) in werking getreden.====>[None]
#####
Voor invoering hiervan gold een algehele scheiding van goederen als wettelijk stelsel in Turkije.====>[None]
#####
Sinds de invoering van het nieuwe wetboek is de algehele scheiding van goederen vervangen door het regime van verwervingsdeelneming.====>[None]
#####
Op grond van de invoeringswet blijft tussen echtgenoten die vóór [datum] zijn gehuwd, zoals in casu het geval is, het oude stelsel gelden.====>[None]
#####
Nu partijen niet hebben gekozen voor toepassing van een ander stelsel, geldt vanaf [datum] voor partijen het nieuwe Turkse wettelijk huwelijksgoederenregime.====>[None]
#####
Dit heeft tot gevolg dat goederen tot [datum] gescheiden blijven, terwijl goederen die vanaf [datum] zijn verkregen door het nieuwe regime van verwervingsdeelneming worden bestreken.====>[None]
#####
De vrouw heeft gesteld dat partijen een gezamenlijke spaarrekening hadden waarvan het saldo moet worden verdee====>[None]
#####
Het had naar het oordeel van het hof op de weg van de vrouw gelegen om haar stelling deugdelijk, met relevante stukken te onderbouwen.====>[None]
#####
De vrouw heeft zulks nagelaten.====>[None]
#####
Zij heeft slechts bij faxbericht van [datum] een stuk betreffende het spaargeld van partijen op een bepaalde datum overgeleg====>[None]
#####
Het hof kan op grond van dit stuk en bij gebreke van overige stukken, niet vaststellen of er ten tijde van het huwelijk sprake was van een spaarrekening, op wiens naam die spaarrekening stond en hoe hoog het eventuele saldo van die spaarrekening was.====>[None]
#####
Evenmin beschikt het hof over stukken waaruit kan worden opgemaakt welk eventueel saldo de bankrekening tot [datum] had en welk saldo nadien daarop is gekomen.====>[None]
#####
Het hof is derhalve van oordeel dat de vrouw haar stelling niet heeft aangetoond noch aannemelijk heeft gemaakt en zal het verzoek van de vrouw, als onvoldoende onderbouwd, afwijzen.====>[None]
#####
De man heeft verzocht de verdeling van de huwelijksgoederengemeenschap te bevelen en deze van deze procedure af te splitsen conform hoofdstuk 9 van het procesreglement.====>[None]
#####
Ter zitting bij het hof heeft hij nog verzocht om, met een beroep op artikel 1.4.7 van het procesreglement verzoekschriftprocedures gerechtshoven, stukken betreffende de verdeling van de huwelijksgoederengemeenschap over te mogen leggen.====>[None]
#####
Het beroep van de man op artikel 1.4.7 van het procesreglement verzoekschriftprocedures gerechtshoven zal het hof afwijzen.====>[None]
#####
Naar het oordeel van het hof heeft de man niet voldaan aan zijn stelplicht door na te laten stukken betreffende de verdeling over te leggen en zijn verzoek te onderbouwen.====>[None]
#####
Daarnaast heeft hij, mede gelet op de duur van de onderhavige procedure, voldoende gelegenheid gehad om deze stukken te overleggen.====>[None]
#####
Dat hij dit niet heeft gedaan dient voor zijn rekening en risico te komen.====>[None]
#####
Het hof zal het verzoek van de man afwijzen.====>[None]
#####
Het hof merkt nog op dat de verwijzing door de man naar hoofdstuk 9 van het procesreglement ziet op het procesreglement verzoekschriftprocedures van de rechtbanken en dat is in deze procedure niet van toepassing.====>[None]
#####
Het procesreglement van de gerechtshoven kent hierover een andere regeling.====>[None]
#####
Gelet op de familierechtelijke aard van de procedure zal het hof de proceskosten in hoger beroep compenseren.====>[None]
#####
Dit leidt tot de volgende beslissing.====>[None]
#####
BESLISSING OP HET HOGER BEROEP Het hof: spreekt tussen partijen, op [datum] 1993 in [woonplaats 2], Turkije, gehuwd, de echtscheiding uit; bepaalt dat vanaf de datum van ontbinding van het huwelijk het gezag over de minderjarigen: - [naam minderjarige 1], geboren op [geboortedag 3] 1998 in Turkije, en - [naam minderjarige 2], geboren op [geboortedag 4] 2003 te Delft, voortaan alleen aan de vrouw toekomt; draagt de griffier van het hof op onverwijld van deze beslissing mededeling te doen aan de griffier van de rechtbank Rotterdam; bepaalt de door de man aan de vrouw te betalen bijdrage in de kosten van verzorging en opvoeding van de minderjarigen met ingang van de datum waarop de echtscheidingsbeschikking zal zijn ingeschreven in de registers van de burgerlijke stand op [geld]- per maand per kind, bij vooruitbetaling te voldoen; bepaalt de uitkering tot levensonderhoud van de vrouw ten laste van de man, met ingang van de datum waarop de echtscheidingsbeschikking zal zijn ingeschreven in de registers van de burgerlijke stand, op [geld]- per maand, wat de na heden te verschijnen termijnen betreft bij vooruitbetaling te voldoen; verklaart deze beschikking tot zover uitvoerbaar bij voorraad; compenseert de kosten van het geding in hoger beroep aldus dat iedere partij de eigen kosten draagt; bekrachtigt de bestreden beschikking voor zover het de compensatie van de proceskosten betreft; wijst het in hoger beroep meer of anders verzochte af.====>[None]
#####
Deze beschikking is gegeven door [naam], [naam], [naam], bijgestaan door [naam] Zeggeren als griffier, en uitgesproken ter openbare terechtzitting van [datum]====>[None]
#####
De Hoge Raad heeft in zijn voornoemde arrest onder 2.1 de feiten vastgesteld, waar het hof van uit gaat.====>[None]
#####
Het gaat kort samengevat om het volgende.====>[None]
#####
[appellante] heeft in 2017 bij een instelling van bijzonder onderwijs eindexamen VWO gedaan.====>[None]
#####
Zij heeft bij het centraal schriftelijk examen Frans een bepaald antwoord gegeven.====>[None]
#####
Dit antwoord is afgekeurd in overeenstemming met het correctievoorschrift.====>[None]
#####
Het College heeft later besloten dat haar antwoord toch goed had moeten worden gereken====>[None]
#####
Het College heeft bij deze stand van zaken besloten een compenserende maatregel te treffen via de zogenoemde normeringster====>[None]
#####
[appellante] heeft, ook na de door het College toegekende compensatie, te weinig punten behaald voor haar diploma VWO.====>[None]
#####
In het kort geding in eerste aanleg heeft [appellante] gevorderd, beknopt weergegeven, om de Staat (het College) op te dragen: - om haar, op de door [appellante] gewenste wijze, in de toestand te brengen waarin zij verkeerd zou hebben indien haar antwoord zou zijn goedgekeurd; - met als resultaat dat de directeur van de school haar op uiterlijk [datum] een VWO diploma zal uitreiken; op straffe van de dwangsom, met veroordeling van de Staat (het College) in de kosten van het geding.====>[None]
#####
Zij heeft aan die vordering ten grondslag gelegd dat de Staat (het College) onrechtmatig jegens haar heeft gehandeld door de fout (het afkeuren van haar antwoord) niet op de door haar voorgestane wijze te corrigeren.====>[None]
#####

In [19]:
### Match sentences to their labels based on the extracted sections ###
# Some sentences may not find a matching label and will be assigned "None"

CASE = []
SENTENCES = []
LABELS = []
for case, text in zip(xml_data.case_name,xml_data.sent_text):
    #print(case + "====>[" + text + "]")
    found  = False
    for labels in case_dict[case]: 
        text_to_check = case_dict[case][labels].lower()
        text_to_check = re.sub(r'\\n+', ' ', text_to_check)
        text_to_check = re.sub(r'\s+', ' ', text_to_check).strip()
        text_to_check = replace_dates_by_month_window(text_to_check)
        text_to_check = replace_money(text_to_check)
        text_to_check = replace_person_names(text_to_check)
        if text.lower() in text_to_check:
            #print("Found label:", labels)
            CASE.append(case)
            SENTENCES.append(text)
            LABELS.append(labels)
            found = True
            break
    if not found:
        #print("Not found:", text)
        CASE.append(case)
        SENTENCES.append(text)
        LABELS.append("None")

model_data = {
    "case_name": CASE,  
    "sent_text": SENTENCES,
    "label": LABELS
}
model_data = pd.DataFrame(model_data)

In [20]:
model_data

,case_name,sent_text,label
0,ECLI:NL:GHAMS:2015:2960.txt,De kantonrechter heeft in het bestreden vonnis...,None
1,ECLI:NL:GHAMS:2015:2960.txt,Deze feiten zijn in hoger beroep niet in gesch...,None
2,ECLI:NL:GHAMS:2015:2960.txt,Op [datum] heeft [geïntimeerde] een bedrag van...,materiele feiten
3,ECLI:NL:GHAMS:2015:2960.txt,Op [datum] heeft [appellante] een schriftelijk...,materiele feiten
4,ECLI:NL:GHAMS:2015:2960.txt,Deze verklaring houdt onder meer in: “Dit bedr...,None
...,...,...,...
8456,ECLI:NL:RBZWB:2015:638.txt,Het bestreden besluit kan in stand blijven.,beoordeling
8457,ECLI:NL:RBZWB:2015:638.txt,Er is geen grond voor een proceskostenveroorde...,None
8458,ECLI:NL:RBZWB:2015:638.txt,De rechtbank verklaart het beroep ongegron,beslissing
8459,ECLI:NL:RBZWB:2015:638.txt,"Deze uitspraak is gedaan door [naam], voorzitt...",None
8460,ECLI:NL:RBZWB:2015:638.txt,De beslissing is in het openbaar uitgesproken ...,None

In [21]:
df_final

,case_name,extracted_data,matched_headers,matched_groups,matched_norm_titles,match_methods,number_of_headers,data,data_clean
0,ECLI:NL:GHAMS:2015:2960.txt,{'Feiten': 'De kantonrechter heeft in het best...,"[Feiten, Beoordeling, Beslissing]","[Feiten, Beoordeling, Beslissing]","[feiten, beoordeling, beslissing]","[exact, exact, exact]",3,De kantonrechter heeft in het bestreden vonnis...,De kantonrechter heeft in het bestreden vonnis...
1,ECLI:NL:GHAMS:2015:5282.txt,{'De gronden van de beslissing': 'Nu van de zi...,"[De gronden van de beslissing, De beslissing]","[Beoordeling, Beslissing]","[de gronden van de beslissing, de beslissing]","[exact, exact]",2,Nu van de zijde van de partijen geen bezwaren ...,Nu van de zijde van de partijen geen bezwaren ...
2,ECLI:NL:GHARL:2016:7748.txt,{'De verdere motivering van de beslissing in h...,[De verdere motivering van de beslissing in ho...,"[Beoordeling, Beslissing]",[de verdere motivering van de beslissing in ho...,"[token_overlap, exact]",2,2.1 Bij voormeld tussenarrest heeft het hof pa...,2.1 Bij voormeld tussenarrest heeft het hof pa...
3,ECLI:NL:GHDHA:2016:706.txt,{'Inhoudelijke beoordeling': '45. Op 1 januari...,"[Inhoudelijke beoordeling, Inhoudelijke beoord...","[Beoordeling, Beoordeling, Beoordeling, Beoord...","[inhoudelijke beoordeling, inhoudelijke beoord...","[fuzzy, fuzzy, fuzzy, fuzzy, fuzzy, fuzzy, fuzzy]",7,45. Op 1 januari 2002 is een nieuw Turks Burge...,45. Op [datum] is een nieuw Turks Burgerlijk W...
4,ECLI:NL:GHSHE:2021:1091.txt,{'De beoordeling': '2.1. De Hoge Raad heeft in...,"[De beoordeling, De uitspraak]","[Beoordeling, Beslissing]","[de beoordeling, de uitspraak]","[exact, exact]",2,2.1. De Hoge Raad heeft in zijn voornoemde arr...,2.1. De Hoge Raad heeft in zijn voornoemde arr...
...,...,...,...,...,...,...,...,...,...
95,ECLI:NL:RBNNE:2018:4847.txt,{'Overwegingen': '1. De rechtbank gaat uit van...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,1. De rechtbank gaat uit van de volgende relev...,1. De rechtbank gaat uit van de volgende relev...
96,ECLI:NL:RBOBR:2019:10.txt,{'Overwegingen': 'De aanleiding voor deze proc...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,De aanleiding voor deze procedure 1. Eiser wil...,De aanleiding voor deze procedure 1. Eiser wil...
97,ECLI:NL:RBOVE:2019:1349.txt,{'Overwegingen': '1.Op 15 oktober 2017 heeft e...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,1.Op 15 oktober 2017 heeft eiser verweerder ve...,1.Op [datum] heeft eiser verweerder verzocht o...
98,ECLI:NL:RBROT:2016:4797.txt,{'Overwegingen': '1. Verweerder heeft aan het ...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,1. Verweerder heeft aan het bestreden besluit ...,1. Verweerder heeft aan het bestreden besluit ...
99,ECLI:NL:RBZWB:2015:638.txt,{'Overwegingen': '1. Op grond van de stukken e...,"[Overwegingen, Beslissing]","[Beoordeling, Beslissing]","[overwegingen, beslissing]","[exact, exact]",2,1.\tOp grond van de stukken en de behandeling ...,1.\tOp grond van de stukken en de behandeling ...

In [22]:
import re
from sentence_splitter import sentence_splitter

spl = sentence_splitter()

def canonical_clean(text: str) -> str:
    """
    One cleaning function used for:
    - section blocks
    - individual sentences
    So substring matching works reliably.
    """
    if text is None:
        return ""

    # 1) your splitter cleaner (keeps paragraphs logic consistent with your pipeline)
    t = spl.clean_block_preserve_paragraphs(str(text))

    # 2) your additional cleaning (exactly as you asked)
    t = re.sub(r'\\n+', ' ', t)          # literal \n (if present)
    t = re.sub(r'\n+', ' ', t)           # real newlines
    t = re.sub(r'\s+', ' ', t).strip()

    t = replace_dates_by_month_window(t)
    t = replace_money(t)
    t = replace_person_names(t)

    # final whitespace normalize
    t = re.sub(r'\s+', ' ', t).strip()
    return t

In [23]:
df_final.extracted_data[0]

{'Feiten': 'De kantonrechter heeft in het bestreden vonnis onder het kopje “De feiten” de feiten vastgesteld die zij tot uitgangspunt heeft genomen. Deze feiten zijn in hoger beroep niet in geschil en dienen derhalve ook het hof als uitgangspunt.',
 'Beoordeling': '3.1. Op 10 oktober 2012 heeft [geïntimeerde] een bedrag van € 15.000,- ter leen verstrekt aan [appellante] in verband met het voornemen van [appellante] een onderneming (verkoop van voedingssupplementen) te beginnen. Op 4/5 januari 2013 heeft [appellante] een schriftelijke verklaring opgesteld, die beide partijen hebben ondertekend. Deze verklaring houdt onder meer in: “Dit bedrag wordt in gedeelten terugbetaald; wanneer er door deze promotie, inschrijvingen en verdiensten in welke vorm dan ook; ontvangen worden; gaat daar zo snel mogelijk het grootste deel direct van terug/retour naar de rekening van dhr. [geïntimeerde] (…) Zoals afgesproken; zo ook: zou er een grote doos met voedingssupplementen ter waarde van € 2.000,= bij dhr. v. Diest terecht komen voor eigen gebruik (…) dit bedrag zou van de lening afgetrokken kunnen + mogen worden, maar nu eind 2012; laatste week; komt dhr. hiervan op zijn schrede terug”. 3.2. [geïntimeerde] vorderde in eerste aanleg (samengevat) nietigverklaring van de tussen partijen gesloten overeenkomst en veroordeling van [appellante] tot betaling van € 15.000,-. In voorwaardelijke reconventie vorderde [appellante] veroordeling van [geïntimeerde] tot betaling van € 6.530,50, te vermeerderen met wettelijke rente. 3.3. De kantonrechter heeft het beroep van [geïntimeerde] op nietigheid van de overeenkomst afgewezen. Zij heeft [appellante] op de voet van artikel 7A:1798 BW veroordeeld tot terugbetaling van de van [geïntimeerde] geleende € 15.000,- in vijf maandelijkse termijnen van € 3.000,- waarvan de eerste vervalt op 1 februari 2014. De kantonrechter heeft de voorwaardelijke vordering in reconventie  - gegrond op de stelling van [appellante] dat [geïntimeerde] voedingssupplementen ten bedrage van € 6.530,50 van haar had gekocht – afgewezen. Zowel in conventie als in reconventie is [appellante] in de proceskosten veroordeeld. De kantonrechter heeft bij vonnis van 13 maart 2014 overwogen dat de beslissing in conventie ten onrechte uitvoerbaar bij voorraad was verklaard en het vonnis van 16 januari 2014 in die zin verbeterd. 3.4. Tegen de beslissingen in het vonnis van 16 januari 2014 komt [appellante] op in hoger beroep. 3.5. Het hof zal eerst grief 2 bespreken. Daarin klaagt [appellante] dat de kantonrechter niet heeft aangenomen dat [geïntimeerde] een doos met voedingssupplementen heeft besteld en afgenomen van haar. Deze grief slaagt. Het staat vast dat [appellante] een doos met voedingssupplementen heeft achtergelaten bij [geïntimeerde] en dat [geïntimeerde] deze op dat moment heeft behouden en in elk geval een aantal van deze voedingssupplementen heeft gebruikt. De lezing van [appellante] dat de waarde van de doos met voedingssupplementen - naar in hoger beroep niet meer in geschil is: € 2.000,- - zou mogen worden afgetrokken van het geleende bedrag van € 15.000,- vindt bovendien steun in de eerdergenoemde brief van [appellante] , die ook door [geïntimeerde] is ondertekend. In het licht van dit een en ander acht het hof de bestrijding door [geïntimeerde] van de lezing van [appellante] onvoldoende gemotiveerd. Het beroep op verrekening slaagt daarom, zodat de terugbetalingsverplichting van [appellante] nog een bedrag van € 13.000,- beloopt. 3.6. Grief 1 strekt ertoe dat het hof de terugbetalingstermijnen opnieuw zal vaststellen en daarbij rekening zal houden met de draagkracht van [appellante] . [appellante] wijst erop dat [geïntimeerde] op de hoogte was van haar financiële positie, wist waar [appellante] het geld voor zou gaan gebruiken en dat er dus een risico bestond dat zij geen omzet/winst zou maken. Zij brengt naar voren dat zij enkel inkomsten heeft uit haar AOW-uitkering van ongeveer € 950,- per maand en dat zij in termijnen van € 50,- zou kunnen terugbetalen. Executoriale verkoop van haar woning zou in de gegeven omstandigheden misbruik van executiebevoegdheid opleveren. Het hof oordeelt als volgt. 3.7. Uit de overeenkomst tussen partijen volgt dat [appellante] het geleende bedrag zal terugbetalen wanneer zij daartoe in staat zal zijn. Ingevolge artikel 7A:1798 BW dient de rechter in zodanig geval de tijd der teruggave te bepalen “naar gelang der omstandigheden”. Op basis van de wederzijdse stellingen van partijen kan worden aangenomen dat [appellante] geen inkomsten meer zal ontvangen uit haar onderneming. Van [appellante] had verwacht mogen worden dat zij ook inzicht zou geven in haar vermogenspositie. Uit haar eigen stellingen volgt dat zij eigenaar is van een woning. Iedere verdere bijzonderheid te dien aanzien – bijvoorbeeld de waarde van die woning, eventuele hypothecaire schuld, eventuele financieringsmogelijkheden in verband met een en ander – is echter achterwege gebleven. Bij gebreke van toereikende gegevens aan de zijde van [appellante] bestaat onvoldoende aanknopingspunt om tot een andere betalingswijze van het resterende bedrag van € 13.000,- te besluiten, zodat grief 1 faalt. 3.8. In grief 3 betoogt [appellante] dat de kantonrechter haar ten onrechte heeft veroordeeld in de proceskosten, zowel in conventie als in voorwaardelijke reconventie. 3.9. Deze grief faalt. Terugbetaling van het geleende bedrag was de inzet van het geding in eerste aanleg in conventie. Het verweer daartegen van [appellante] is verworpen. De omstandigheid dat de uitkomst is dat niet € 15.000,- maar € 13.000,- dient te worden terugbetaald en dat terugbetaling mogelijk is in een aantal termijnen, neemt niet weg dat [appellante] als de overwegend in het ongelijk gestelde partij moet worden aangemerkt. Dat geldt ook ten aanzien van de voorwaardelijk ingestelde vordering in reconventie nu [appellante] in eerste aanleg nog een bedrag vorderde van € 6.530,50 en zich niet heeft beperkt tot het bedrag van € 2.000,- dat volgens haar eigen stellingen in hoger beroep tussen partijen was afgesproken. 3.10. Het bestreden vonnis zal worden vernietigd, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan € 13.000,-. Het hof zal in zoverre opnieuw recht doen. 3.11. [appellante] zal als de overwegend in het ongelijk gestelde partij worden veroordeeld in de kosten van het hoger beroep.',
 'Beslissing': 'Het hof: vernietigt het vonnis waarvan beroep, doch uitsluitend voor zover [appellante] daarbij is veroordeeld tot terugbetaling van een hoger bedrag dan € 13.000,-; in zoverre opnieuw rechtdoende: veroordeelt [appellante] tot betaling aan [geïntimeerde] van een bedrag van € 13.000,-, bepaalt dat voor “vijf maandelijkse termijnen van € 3.000,00” gelezen moet worden: vier maandelijkse termijnen van € 3.000,- en één termijn van € 1.000,- en wijst het meer gevorderde af; bekrachtigt het vonnis voor het overige; veroordeelt [appellante] in de kosten van het geding in hoger beroep, tot op heden aan de zijde van [geïntimeerde] begroot op € 704,- aan verschotten en € 894,- voor salaris; verklaart dit arrest uitvoerbaar bij voorraad. Dit arrest is gewezen door mrs. J.E. Molenaar, C.M. Aarts en R.J.F. Thiessen en door de rolraadsheer in het openbaar uitgesproken op 14 juli 2015.'}

In [24]:
import pandas as pd

SECTIONS_DF_NAME = "df_final"   # <- replace with your actual df name
sections_df = globals()[SECTIONS_DF_NAME]

assert "case_name" in sections_df.columns, "sections_df must have case_name"
assert "extracted_data" in sections_df.columns, "sections_df must have extracted_data"
assert "case_name" in model_data.columns, "model_data must have case_name"
assert "sent_text" in model_data.columns, "model_data must have sent_text"

print("sections_df shape:", sections_df.shape)
print("model_data shape:", model_data.shape)

# Build lookup: case_name -> extracted_data dict
case2sections = dict(zip(sections_df["case_name"], sections_df["extracted_data"]))

# Output columns
model_data["hdr_title"] = None
model_data["hdr_match"] = 0

total = len(model_data)
matched = 0

matched_examples = []
unmatched_examples = []

for case_name, case_df in model_data.groupby("case_name", sort=False):
    sec_dict = case2sections.get(case_name)

    if not isinstance(sec_dict, dict) or len(sec_dict) == 0:
        continue

    # Clean ALL blocks once
    headers = []
    blocks_clean = []
    for hdr, block in sec_dict.items():
        if block is None or not str(block).strip():
            continue
        headers.append(hdr)
        blocks_clean.append(canonical_clean(block))

    if not headers:
        continue

    # Assign each sentence to FIRST matching header block
    for idx, sent in zip(case_df.index.tolist(), case_df["sent_text"].tolist()):
        s_clean = canonical_clean(sent)
        if not s_clean:
            continue

        found_hdr = None
        for hdr, b_clean in zip(headers, blocks_clean):
            if s_clean in b_clean:
                found_hdr = hdr
                break

        if found_hdr is not None:
            model_data.at[idx, "hdr_title"] = found_hdr
            model_data.at[idx, "hdr_match"] = 1
            matched += 1
            if len(matched_examples) < 12:
                matched_examples.append((case_name, found_hdr, sent[:160]))
        else:
            if len(unmatched_examples) < 12:
                unmatched_examples.append((case_name, sent[:160]))

print("\n=== HEADER MATCH RESULTS ===")
print("Total sentences:", total)
print("Matched sentences:", matched)
print("Coverage:", round(matched / max(1, total), 3))

print("\n--- Matched examples (up to 12) ---")
for c, h, s in matched_examples:
    print(f"CASE={c} | HDR={h} | SENT={s}")

print("\n--- Unmatched examples (up to 12) ---")
for c, s in unmatched_examples:
    print(f"CASE={c} | SENT={s}")

print("\nTop hdr_title values (including NaN):")
print(model_data["hdr_title"].value_counts(dropna=False).head(20))

sections_df shape: (100, 9)
model_data shape: (8461, 3)

=== HEADER MATCH RESULTS ===
Total sentences: 8461
Matched sentences: 8391
Coverage: 0.992

--- Matched examples (up to 12) ---
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Feiten | SENT=De kantonrechter heeft in het bestreden vonnis onder het kopje “De feiten” de feiten vastgesteld die zij tot uitgangspunt heeft genomen.
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Feiten | SENT=Deze feiten zijn in hoger beroep niet in geschil en dienen derhalve ook het hof als uitgangspunt.
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=Op [datum] heeft [geïntimeerde] een bedrag van [geld]- ter leen verstrekt aan [appellante] in verband met het voornemen van [appellante] een onderneming (verkoo
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=Op [datum] heeft [appellante] een schriftelijke verklaring opgesteld, die beide partijen hebben onderteken
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=Deze verklaring houdt onder meer in: “Dit bedrag wordt in gedeelten terugbetaald; wanneer er door deze promotie, inschrijvingen en verdiensten in welke vorm dan
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=[geïntimeerde] (...) Zoals afgesproken; zo ook: zou er een grote doos met voedingssupplementen ter waarde van [geld]= bij dhr.
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=Diest terecht komen voor eigen gebruik (...) dit bedrag zou van de lening afgetrokken kunnen + mogen worden, maar nu eind 2012; laatste week; komt dhr. hiervan
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=[geïntimeerde] vorderde in eerste aanleg (samengevat) nietigverklaring van de tussen partijen gesloten overeenkomst en veroordeling van [appellante] tot betalin
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=In voorwaardelijke reconventie vorderde [appellante] veroordeling van [geïntimeerde] tot betaling van [geld] te vermeerderen met wettelijke rente.
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=De kantonrechter heeft het beroep van [geïntimeerde] op nietigheid van de overeenkomst afgewezen.
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=Zij heeft [appellante] op de voet van artikel 7A:1798 BW veroordeeld tot terugbetaling van de van [geïntimeerde] geleende [geld]- in vijf maandelijkse termijnen
CASE=ECLI:NL:GHAMS:2015:2960.txt | HDR=Beoordeling | SENT=Zowel in conventie als in reconventie is [appellante] in de proceskosten veroordee

--- Unmatched examples (up to 12) ---
CASE=ECLI:NL:HR:2016:339.txt | SENT=De advocaat van [verweerster] heeft dat bij brief van [datum] gedaan.3.1 In cassatie kan van het volgende worden uitgegaan. i) Fitness Carnisselande exploiteert
CASE=ECLI:NL:HR:2016:339.txt | SENT=(rov. 5) Het hof heeft vervolgens, voor zover in cassatie van belang, het eindvonnis vernietigd voor zover Fitness Carnisselande c.s. daarbij hoofdelijk zijn ve
CASE=ECLI:NL:HR:2016:339.txt | SENT=Dit arrest is gewezen door de vice-president [naam] als voorzitter en de raadsheren [naam], [naam], [naam] en [naam], en in het openbaar uitgesproken door de ra
CASE=ECLI:NL:RBDHA:2015:12417.txt | SENT=Tine Kristin Elza Katrien Strous-Delaere beiden kantoorhoudende te Den Haag, verzoekers, in hun hoedanigheid van vereffenaars van de nalatenschap van Johanna Ph
CASE=ECLI:NL:RBGEL:2020:3538.txt | SENT=De behandeling van het verzoekschrift is gepland op [datum] conventie
CASE=ECLI:NL:RBMNE:2017:2160.txt | SENT=Bij beschikking van [datum] is de ondertoezichtstelling van [minderjarige 1] verlengd tot [datum] Bij beschikking van [datum] is [minderjarige 2] onder toezicht
CASE=ECLI:NL:RBNHO:2021:1436.txt | SENT=Bij het rapport van Esdeo-Bouwadvies is onder meer een tekening gevoegd met de titel “ Inhoud totale woning ”, waarin het volgende is vermeld:in de hoofdzaak
CASE=ECLI:NL:RBNHO:2021:1436.txt | SENT=Op de stellingen van partijen wordt hierna, voor zover van belang, nader ingegaan.in de hoofdzaak primair: dwaling
CASE=ECLI:NL:RBOBR:2020:3584.txt | SENT=Op 31 [datum] heeft de Raad van Bestuur een bericht gestuurd aan alle partners van BDO Holding, de Raad van Commissarissen en de Stafhoofden met het bericht dat
CASE=ECLI:NL:RBOBR:2020:3584.txt | SENT=De kosten aan de zijde van BDO Holding worden begroot op: - griffierecht € 2.042,00 - overige kosten 0,00 - salaris advocaat 980,00 Totaal € 3.022,00De voorzien
CASE=ECLI:NL:RBOVE:2015:4122.txt | SENT=[datum] blijkt dat het UWV van mening is dat de door de werkgever uitgevoerde re-integratie-inspanningen voldoende zijn geweest.3.1 [X] verzoekt de kantonrechte
CASE=ECLI:NL:RBOVE:2015:4122.txt | SENT=Tevens wil Selo, ondanks de arbeidsongeschiktheid van [X] [datum] [X] onverkort houden aan een concurrentie- en relatiebeding voor de duur van twee jaar in gehe

Top hdr_title values (including NaN):
hdr_title
Overwegingen                                                                                                                                                                                                                                                                                                                                          1405
De beoordeling                                                                                                                                                                                                                                                                                                                                        1009
De feiten                                                                                                                                                                                                                                                                                                                                              634
Beoordeling van het geschil                                                                                                                                                                                                                                                                                                                            338
Beslissing                                                                                                                                                                                                                                                                                                                                             317
Feiten                                                                                                                                                                                                                                                                                                                                                 249
De beoordeling van het bewijs                                                                                                                                                                                                                                                                                                                          213
De strafoplegging                                                                                                                                                                                                                                                                                                                                      194
Beoordeling van het middel                                                                                                                                                                                                                                                                                                                             189
Beoordeling van het hoger beroep                                                                                                                                                                                                                                                                                                                       185
De beslissing                                                                                                                                                                                                                                                                                                                                          183
Het geschil                                                                                                                                                                                                                                                                                                                                            180
Bewezenverklaring en bewijsvoering                                                                                                                                                                                                                                                                                                                     172
Beoordeling van het bewijs                                                                                                                                                                                                                                                                                                                             167
Beoordeling                                                                                                                                                                                                                                                                                                                                            156
De strafbaarheid van het feit en van verdachte                                                                                                                                                                                                                                                                                                         115
Geschil11. In geschil is de hoogte van de verschuldigde overdrachtsbelasting. Meer specifiek is in geschil of de artikelen 7 en 12 van de Wet BRV, dan wel de zogenoemde ‘doorkijkarresten’ van de Hoge Raad van 23 februari 2007 (nr. 41591, ECLI:NL:HR2007:AU8559) en van 10 juni 2011 (nr. 10/00498, ECLI:NL:HR:2011:BQ7580) toepassing vinden.     111
Gronden                                                                                                                                                                                                                                                                                                                                                107
Motivering van de straffen en maatregelen                                                                                                                                                                                                                                                                                                              107
De vaststaande feiten                                                                                                                                                                                                                                                                                                                                  103
Name: count, dtype: int64

In [25]:
model_data

,case_name,sent_text,label,hdr_title,hdr_match
0,ECLI:NL:GHAMS:2015:2960.txt,De kantonrechter heeft in het bestreden vonnis...,None,Feiten,1
1,ECLI:NL:GHAMS:2015:2960.txt,Deze feiten zijn in hoger beroep niet in gesch...,None,Feiten,1
2,ECLI:NL:GHAMS:2015:2960.txt,Op [datum] heeft [geïntimeerde] een bedrag van...,materiele feiten,Beoordeling,1
3,ECLI:NL:GHAMS:2015:2960.txt,Op [datum] heeft [appellante] een schriftelijk...,materiele feiten,Beoordeling,1
4,ECLI:NL:GHAMS:2015:2960.txt,Deze verklaring houdt onder meer in: “Dit bedr...,None,Beoordeling,1
...,...,...,...,...,...
8456,ECLI:NL:RBZWB:2015:638.txt,Het bestreden besluit kan in stand blijven.,beoordeling,Overwegingen,1
8457,ECLI:NL:RBZWB:2015:638.txt,Er is geen grond voor een proceskostenveroorde...,None,Overwegingen,1
8458,ECLI:NL:RBZWB:2015:638.txt,De rechtbank verklaart het beroep ongegron,beslissing,Beslissing,1
8459,ECLI:NL:RBZWB:2015:638.txt,"Deze uitspraak is gedaan door [naam], voorzitt...",None,Beslissing,1
8460,ECLI:NL:RBZWB:2015:638.txt,De beslissing is in het openbaar uitgesproken ...,None,Beslissing,1

In [26]:
# df_sent = your sentence-level dataframe (the one with hdr_title)
# header_group_dict = { "Beoordeling": [...headers...], "Feiten": [...], ... }

# 1) Invert mapping: header -> group
header_to_group = {
    header: group
    for group, headers in header_group_dict.items()
    for header in headers
}

# 2) Assign group based on hdr_title; default "Other" if not found
model_data["hdr_group"] = model_data["hdr_title"].map(header_to_group).fillna("Other")

# (optional) quick check
model_data["hdr_group"].value_counts()

hdr_group
Beoordeling                   5122
Feiten                        1208
Beslissing                     964
Proceshandelingen partijen     855
Context                        242
Other                           70
Name: count, dtype: int64

In [27]:
model_data

,case_name,sent_text,label,hdr_title,hdr_match,hdr_group
0,ECLI:NL:GHAMS:2015:2960.txt,De kantonrechter heeft in het bestreden vonnis...,None,Feiten,1,Feiten
1,ECLI:NL:GHAMS:2015:2960.txt,Deze feiten zijn in hoger beroep niet in gesch...,None,Feiten,1,Feiten
2,ECLI:NL:GHAMS:2015:2960.txt,Op [datum] heeft [geïntimeerde] een bedrag van...,materiele feiten,Beoordeling,1,Beoordeling
3,ECLI:NL:GHAMS:2015:2960.txt,Op [datum] heeft [appellante] een schriftelijk...,materiele feiten,Beoordeling,1,Beoordeling
4,ECLI:NL:GHAMS:2015:2960.txt,Deze verklaring houdt onder meer in: “Dit bedr...,None,Beoordeling,1,Beoordeling
...,...,...,...,...,...,...
8456,ECLI:NL:RBZWB:2015:638.txt,Het bestreden besluit kan in stand blijven.,beoordeling,Overwegingen,1,Beoordeling
8457,ECLI:NL:RBZWB:2015:638.txt,Er is geen grond voor een proceskostenveroorde...,None,Overwegingen,1,Beoordeling
8458,ECLI:NL:RBZWB:2015:638.txt,De rechtbank verklaart het beroep ongegron,beslissing,Beslissing,1,Beslissing
8459,ECLI:NL:RBZWB:2015:638.txt,"Deze uitspraak is gedaan door [naam], voorzitt...",None,Beslissing,1,Beslissing
8460,ECLI:NL:RBZWB:2015:638.txt,De beslissing is in het openbaar uitgesproken ...,None,Beslissing,1,Beslissing

In [28]:
model_data.case_name.nunique()

100

In [29]:
model_data = model_data[model_data.hdr_group!='Other']

In [30]:
model_data['label'].value_counts()

label
None                 3060
beoordeling          2293
materiele feiten     1529
proceshandelingen    1263
beslissing            246
Name: count, dtype: int64

In [31]:
model_data.hdr_title.nunique()

143

In [32]:
import json

hdr_group_to_titles = (
    model_data.groupby("hdr_group")["hdr_title"]
      .unique()
      .apply(list)
      .to_dict()
)

with open("hdr_group_to_titles.json", "w", encoding="utf-8") as f:
    json.dump(hdr_group_to_titles, f, ensure_ascii=False, indent=2)

hdr_group_to_titles

{'Beoordeling': ['Beoordeling',
  'De gronden van de beslissing',
  'De verdere motivering van de beslissing in hoger beroep',
  'Inhoudelijke beoordeling',
  'De beoordeling',
  'Beoordeling van het middel in het principale beroep',
  'Beoordeling van het middel in het incidentele beroep',
  'Het verzoek en de beoordeling',
  'De beoordeling in conventie',
  'De beoordeling in reconventie',
  'Kwalificatie van het bewezen verklaarde',
  'Het hoger beroep',
  'Bewezenverklaring',
  'Strafbaarheid van het bewezenverklaarde',
  'Strafbaarheid van de verdachte',
  'Bewezenverklaring en bewijsvoering',
  'Aan de beoordeling van het middel voorafgaande opmerkingen',
  'Waardering van het bewijs',
  'De strafbaarheid van het feit en van verdachte',
  'De strafbaarheid van het bewezenverklaarde en de verdachte',
  'De kwalificatie van het bewezenverklaarde',
  'De strafbaarheid van het feit',
  'De strafbaarheid van de verdachte',
  'Overwegingen ten aanzien van straf en/of maatregel',
  'De beoordeling van het bewijs',
  'De strafbaarheid van het bewezenverklaarde',
  'De straf en/of de maatregel',
  'Beoordeling van het bewijs',
  'Kwalificatie en strafbaarheid van de feiten',
  'Strafbaarheid van verdachte',
  'Motivering van de sanctie',
  'Strafbaarheid van het bewezen verklaarde',
  'De bewezenverklaring.',
  'De strafbaarheid van het feit.',
  'De strafbaarheid van verdachte.',
  'Het oordeel van de rechtbank.',
  'De strafbaarheid van het bewezen verklaarde',
  'De strafbaarheid',
  'Beoordeling van het geschil',
  'Beoordeling van het hoger beroep',
  'Oordeel van de Rechtbank',
  'Beoordeling van de middelen',
  'Overwegingen',
  'BEOORDELING VAN HET HOGER BEROEP',
  'BESLISSING OP HET HOGER BEROEP',
  'De ontvankelijkheid van het beroep',
  'Beoordeling van het middel',
  'Het geschil en de beoordeling in het incident',
  'De beoordeling in conventie en in reconventie',
  'De verdere beoordeling',
  'De strafbaarheid van de feiten',
  'De strafbaarheid van verdachte',
  'Motivering van de straffen en maatregelen',
  'BEOORDELING VAN DE VORDERING',
  'Bewijs',
  'Kwalificatie en strafbaarheid van het feit',
  'Motivering van de sancties',
  'Redengeving bewezenverklaring',
  'Ten aanzien van feit 2.',
  'Ten aanzien van feit 3.',
  'De bewezenverklaring'],
 'Beslissing': ['Beslissing',
  'De beslissing',
  'De uitspraak',
  'BESLISSING',
  'Vrijspraak',
  'Oplegging van straf',
  'Slotsom',
  'De strafoplegging',
  'DE UITSPRAAK VAN DE RECHTBANK LUIDT:',
  'DE UITSPRAAK',
  'Beslissing op de vordering van de benadeelde partij [slachtoffer 2] :',
  'Beslissing op de vordering van de benadeelde partij [slachtoffer 3] :',
  'De op te leggen straf of maatregel',
  '6. Beslissing',
  'Oplegging van straffen',
  'De straf'],
 'Context': ['Onderzoek van de zaak',
  'Het onderzoek ter terechtzitting',
  'Voorvragen',
  'Het onderzoek op de terechtzitting',
  'De formele voorvragen.',
  'De voorvragen',
  'Gronden',
  'Grondslag en inhoud van het EAB'],
 'Feiten': ['Feiten',
  'Uitgangspunten in cassatie',
  'De feiten',
  'De relevante feiten',
  'De vaststaande feiten',
  'Bewijsoverweging ten aanzien van de feiten 1 en 2.',
  'Vaststaande feiten',
  'PROCESVERLOOP IN EERSTE AANLEG EN VASTSTAANDE FEITEN',
  'De feiten en de rechtsgang',
  'Feiten waarvoor de toetsing van dubbele strafbaarheid is vereist'],
 'Proceshandelingen partijen': ['Het geding in cassatie',
  'Het geschil',
  'Beschikking op het verzoek van:',
  'De standpunten',
  'Standpunt van de vrouw',
  'Standpunt van de man',
  'Het verzoek',
  'Het verweer',
  'Tenlastelegging',
  'Vordering van het openbaar ministerie',
  'Vordering tenuitvoerlegging',
  'De tenlastelegging',
  'Vordering van de benadeelde partij [benadeelde partij]',
  'Vordering van de benadeelde partij [benadeelde partij 1]',
  'Vordering van de benadeelde partij [benadeelde partij 2]',
  'Vordering van de benadeelde partij [benadeelde partij 3]',
  'Vordering van de benadeelde partij [benadeelde partij 4]',
  'Vordering van de benadeelde partij [benadeelde partij 5]',
  'Geding in cassatie',
  'De vordering van de benadeelde partij',
  'De inhoud van de tenlastelegging',
  'Vordering benadeelde partij en schadevergoedingsmaatregel',
  'Vordering officier van justitie',
  'De tenlastelegging.',
  'De eis van de officier van justitie.',
  'Het verzoek om aanhouding.',
  'De vordering van de benadeelde partij [slachtoffer 2] . De rechtbank acht toewijsbaar, als rechtstreeks door het bewezen verklaarde feit toegebrachte schade, de volgende onderdelen van de vordering te weten immateriële schadevergoeding € 250,-- en materiële schadevergoeding van € 7,78 vermeerderd met de wettelijke rente vanaf 23 mei 2015 tot aan de dag der algehele voldoening.',
  'De vordering van de benadeelde partij [slachtoffer 3] . De rechtbank acht toewijsbaar, als rechtstreeks door het bewezen verklaarde feit toegebrachte schade, de volgende onderdelen van de vordering te weten immateriële schadevergoeding € 250,-- en materiële schadevergoeding van € 7,78 vermeerderd met de wettelijke rente vanaf 23 mei 2015 tot aan de dag der algehele voldoening.',
  'De ontvankelijkheid van de officier van justitie in haar vordering',
  'Omschrijving geschil in hoger beroep en conclusies van partijen',
  'Geschil, alsmede standpunten en conclusies van partijen',
  'Geschil11. In geschil is de hoogte van de verschuldigde overdrachtsbelasting. Meer specifiek is in geschil of de artikelen 7 en 12 van de Wet BRV, dan wel de zogenoemde ‘doorkijkarresten’ van de Hoge Raad van 23 februari 2007 (nr. 41591, ECLI:NL:HR2007:AU8559) en van 10 juni 2011 (nr. 10/00498, ECLI:NL:HR:2011:BQ7580) toepassing vinden.',
  'Het geschil in hoger beroep',
  'De vordering in de hoofdzaak',
  'De vordering in conventie',
  'De vordering in reconventie',
  'Het verweer in reconventie',
  'Het standpunt van [A]',
  'De standpunten ter zitting',
  'Vordering van de benadeelde partij [benadeelde]',
  'De vordering van de benadeelde partij / de schadevergoedingsmaatregel',
  'De vordering tenuitvoerlegging',
  'Vordering tot tenuitvoerlegging',
  'Het standpunt van de officier van justitie.De officier van justitie acht het onder feit 1 primair, feit 2 en feit 3 ten laste gelegde wettig en overtuigend bewezen.',
  'Eis officier van justitie',
  'De vordering tot tenuitvoerlegging',
  'Geschil',
  'Omschrijving geschil na verwijzing en conclusies van partijen']}

In [33]:
model_data

,case_name,sent_text,label,hdr_title,hdr_match,hdr_group
0,ECLI:NL:GHAMS:2015:2960.txt,De kantonrechter heeft in het bestreden vonnis...,None,Feiten,1,Feiten
1,ECLI:NL:GHAMS:2015:2960.txt,Deze feiten zijn in hoger beroep niet in gesch...,None,Feiten,1,Feiten
2,ECLI:NL:GHAMS:2015:2960.txt,Op [datum] heeft [geïntimeerde] een bedrag van...,materiele feiten,Beoordeling,1,Beoordeling
3,ECLI:NL:GHAMS:2015:2960.txt,Op [datum] heeft [appellante] een schriftelijk...,materiele feiten,Beoordeling,1,Beoordeling
4,ECLI:NL:GHAMS:2015:2960.txt,Deze verklaring houdt onder meer in: “Dit bedr...,None,Beoordeling,1,Beoordeling
...,...,...,...,...,...,...
8456,ECLI:NL:RBZWB:2015:638.txt,Het bestreden besluit kan in stand blijven.,beoordeling,Overwegingen,1,Beoordeling
8457,ECLI:NL:RBZWB:2015:638.txt,Er is geen grond voor een proceskostenveroorde...,None,Overwegingen,1,Beoordeling
8458,ECLI:NL:RBZWB:2015:638.txt,De rechtbank verklaart het beroep ongegron,beslissing,Beslissing,1,Beslissing
8459,ECLI:NL:RBZWB:2015:638.txt,"Deze uitspraak is gedaan door [naam], voorzitt...",None,Beslissing,1,Beslissing
8460,ECLI:NL:RBZWB:2015:638.txt,De beslissing is in het openbaar uitgesproken ...,None,Beslissing,1,Beslissing

In [34]:
df = model_data.copy()

df["y_labelled"] = (df["label"] != "None").astype(int)

df["y_labelled"].value_counts()

y_labelled
1    5331
0    3060
Name: count, dtype: int64

In [35]:
df["y_labelled"].value_counts(normalize=True)

y_labelled
1    0.635324
0    0.364676
Name: proportion, dtype: float64

In [36]:
print("Total rows:", len(df))
print("Unique cases:", df["case_name"].nunique())
print(df.groupby("y_labelled").size())

Total rows: 8391
Unique cases: 100
y_labelled
0    3060
1    5331
dtype: int64

## Train Test Split

In [37]:
from sklearn.model_selection import GroupShuffleSplit
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer


# ============================================================
# 1) TRAIN / EVAL / TEST SPLIT (case-level, one-time)
# ============================================================

# First split: train+eval vs test (80 / 20)
gss1 = GroupShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
train_eval_idx, test_idx = next(
    gss1.split(df, groups=df["case_name"])
)

train_eval_df = df.iloc[train_eval_idx].reset_index(drop=True)
test_df = df.iloc[test_idx].reset_index(drop=True)

# Second split: train vs eval (75 / 25 of train_eval → 60 / 20 overall)
gss2 = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=42)
train_idx, eval_idx = next(
    gss2.split(train_eval_df, groups=train_eval_df["case_name"])
)

train_df = train_eval_df.iloc[train_idx].reset_index(drop=True)
eval_df  = train_eval_df.iloc[eval_idx].reset_index(drop=True)

# Quick sanity checks
print("Train:", len(train_df))
print("Eval :", len(eval_df))
print("Test :", len(test_df))

print("Labelled rate:",
      train_df["y_labelled"].mean().round(3),
      eval_df["y_labelled"].mean().round(3),
      test_df["y_labelled"].mean().round(3))

# ============================================================
from datasets import Dataset

# ============================================================
# 2) HF DATASETS (binary: text -> y_labelled)
# ============================================================

train_ds = Dataset.from_pandas(
    train_df[["sent_text", "y_labelled"]]
    .rename(columns={"sent_text": "text", "y_labelled": "labels"})
)

eval_ds = Dataset.from_pandas(
    eval_df[["sent_text", "y_labelled"]]
    .rename(columns={"sent_text": "text", "y_labelled": "labels"})
)

test_ds = Dataset.from_pandas(
    test_df[["sent_text", "y_labelled"]]
    .rename(columns={"sent_text": "text", "y_labelled": "labels"})
)

# ============================================================
# 3) MODEL DEFINITION & TOKENIZATION (shared preprocessing)
# ============================================================
model_name = "GroNLP/bert-base-dutch-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

def tok(batch):
    return tokenizer(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

train_ds = train_ds.map(tok, batched=True)
eval_ds  = eval_ds.map(tok, batched=True)
test_ds  = test_ds.map(tok, batched=True)

Train: 5608
Eval : 1281
Test : 1502
Labelled rate: 0.644 0.593 0.64

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at GroNLP/bert-base-dutch-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/5608 [00:00<?, ? examples/s]

Map:   0%|          | 0/1281 [00:00<?, ? examples/s]

Map:   0%|          | 0/1502 [00:00<?, ? examples/s]

## Helper Function

In [38]:
import os, json
from datetime import datetime

best_models = {}  # global registry (in-memory; optionally saved to disk)

def register_best_model(
    registry: dict,
    model_key: str,
    trainer,
    tokenizer,
    base_save_dir: str = "models",
    extra_meta: dict | None = None,
):
    """
    Save best model + tokenizer from a HuggingFace Trainer run to a stable folder,
    and register metadata in `registry`.

    Parameters
    ----------
    registry : dict
        A dict that will store metadata for saved models (e.g., best_models).
    model_key : str
        Unique key for this model (e.g., "stage1_gatekeeper").
    trainer : transformers.Trainer
        Trainer instance used for training.
    tokenizer :
        Tokenizer used for training.
    base_save_dir : str
        Root directory where models will be saved.
    extra_meta : dict | None
        Optional metadata to store (stage, task, labels, dataset version, etc.)
    """
    best_ckpt = trainer.state.best_model_checkpoint
    if best_ckpt is None:
        raise ValueError(
            "No best_model_checkpoint found. Did you set evaluation_strategy and load_best_model_at_end=True?"
        )

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    save_path = os.path.join(base_save_dir, f"{model_key}_best_{timestamp}")
    os.makedirs(save_path, exist_ok=True)

    trainer.model.save_pretrained(save_path)
    tokenizer.save_pretrained(save_path)

    meta = {
        "model_key": model_key,
        "saved_path": save_path,
        "best_checkpoint": best_ckpt,
        "time_saved": timestamp,
        "training_args": trainer.args.to_dict() if hasattr(trainer, "args") else None,
        "global_step": getattr(trainer.state, "global_step", None),
        "best_metric": getattr(trainer.state, "best_metric", None),
        "best_model_checkpoint": getattr(trainer.state, "best_model_checkpoint", None),
    }
    if extra_meta:
        meta.update(extra_meta)

    registry[model_key] = meta

    with open(os.path.join(save_path, "meta.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2, ensure_ascii=False)

    return meta

train_df

In [39]:
train_df

,case_name,sent_text,label,hdr_title,hdr_match,hdr_group,y_labelled
0,ECLI:NL:GHARL:2016:7748.txt,Bij voormeld tussenarrest heeft het hof partij...,None,De verdere motivering van de beslissing in hog...,1,Beoordeling,0
1,ECLI:NL:GHARL:2016:7748.txt,Ter onderbouwing van zijn stelling dat er geen...,proceshandelingen,De verdere motivering van de beslissing in hog...,1,Beoordeling,1
2,ECLI:NL:GHARL:2016:7748.txt,Ook volgens [geïntimeerde] is het hof gebonden...,None,De verdere motivering van de beslissing in hog...,1,Beoordeling,0
3,ECLI:NL:GHARL:2016:7748.txt,Hetgeen [appellant] met verwijzing naar de als...,beoordeling,De verdere motivering van de beslissing in hog...,1,Beoordeling,1
4,ECLI:NL:GHARL:2016:7748.txt,Daaruit blijkt dat [appellant] zich jegens [ge...,beoordeling,De verdere motivering van de beslissing in hog...,1,Beoordeling,1
...,...,...,...,...,...,...,...
5603,ECLI:NL:RBZWB:2015:638.txt,Het bestreden besluit kan in stand blijven.,beoordeling,Overwegingen,1,Beoordeling,1
5604,ECLI:NL:RBZWB:2015:638.txt,Er is geen grond voor een proceskostenveroorde...,None,Overwegingen,1,Beoordeling,0
5605,ECLI:NL:RBZWB:2015:638.txt,De rechtbank verklaart het beroep ongegron,beslissing,Beslissing,1,Beslissing,1
5606,ECLI:NL:RBZWB:2015:638.txt,"Deze uitspraak is gedaan door [naam], voorzitt...",None,Beslissing,1,Beslissing,0
5607,ECLI:NL:RBZWB:2015:638.txt,De beslissing is in het openbaar uitgesproken ...,None,Beslissing,1,Beslissing,0

# Training

## 1. Full 5 way classification

### Training

In [43]:
# ============================================================
# TRAIN TEXT-ONLY 5-WAY CLASSIFIER (RobBERT)
# Uses frozen splits: train_df / eval_df / test_df
# ============================================================

import numpy as np
import torch
from torch.utils.data import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import f1_score, accuracy_score

# ------------------------------------------------------------
# 1) Config + label mapping (fixed order!)
# ------------------------------------------------------------
MODEL_NAME = "GroNLP/bert-base-dutch-cased"

LEGAL_LABELS = ["None", "beoordeling", "beslissing", "materiele feiten", "proceshandelingen"]
label2id = {l: i for i, l in enumerate(LEGAL_LABELS)}
id2label = {i: l for l, i in label2id.items()}

train_legal = train_df.copy()
eval_legal  = eval_df.copy()
test_legal  = test_df.copy()   # keep untouched; evaluate later

train_legal["y"] = train_legal["label"].map(label2id)
eval_legal["y"]  = eval_legal["label"].map(label2id)
test_legal["y"]  = test_legal["label"].map(label2id)

# ------------------------------------------------------------
# 3) Tokenizer
# ------------------------------------------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# ------------------------------------------------------------
# 4) Torch Dataset wrapper (text -> tokenized tensors)
# ------------------------------------------------------------
class TextDataset(Dataset):
    def __init__(self, df, text_col="sent_text", label_col="y", tokenizer=None, max_len=256):
        self.texts = df[text_col].astype(str).tolist()
        self.labels = df[label_col].astype(int).tolist()
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

train_ds_5 = TextDataset(train_legal, tokenizer=tokenizer, max_len=256)
eval_ds_5  = TextDataset(eval_legal,  tokenizer=tokenizer, max_len=256)
test_ds_5  = TextDataset(test_legal,  tokenizer=tokenizer, max_len=256)

# ------------------------------------------------------------
# 5) Model
# ------------------------------------------------------------
model_5 = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(LEGAL_LABELS),
    id2label=id2label,
    label2id=label2id
)

# ------------------------------------------------------------
# 6) Metrics (5-way)
# ------------------------------------------------------------
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "macro_f1": f1_score(labels, preds, average="macro"),
        "micro_f1": f1_score(labels, preds, average="micro"),
    }

# ------------------------------------------------------------
# 7) Training arguments
# ------------------------------------------------------------
training_args_5 = TrainingArguments(
    output_dir="./text_only_model_5",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    logging_steps=50,
    report_to="none",
    fp16=True
)

# ------------------------------------------------------------
# 8) Trainer (IMPORTANT: eval_dataset = eval_ds_4, not test)
# ------------------------------------------------------------
trainer_5 = Trainer(
    model=model_5,
    args=training_args_5,
    train_dataset=train_ds_5,
    eval_dataset=eval_ds_5,          #validation split
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

# ------------------------------------------------------------
# 9) Train Stage 2A
# ------------------------------------------------------------
trainer_5.train()

# ------------------------------------------------------------
# 10) Save best Stage 2A model into registry
# ------------------------------------------------------------

os.makedirs("models", exist_ok=True)

if "best_models" not in globals():
    best_models = {}

stage2a_meta = register_best_model(
    registry=best_models,
    model_key="text_only_5way",
    trainer=trainer_5,
    tokenizer=tokenizer,
    base_save_dir="models",
    extra_meta={
        "stage": 0,
        "experiment": "1",
        "variant": "text_only",
        "task": "5_way_legal_role_classification",
        "model_name": MODEL_NAME,
        "labels_order": LEGAL_LABELS,
        "text_col": "sent_text",
        "max_len": 256,
        "train_rows": len(train_legal),
        "eval_rows": len(eval_legal),
        "test_rows": len(test_legal),
    }
)

print("✅ Saved 5way best model to:", stage2a_meta["saved_path"])
print("Registry keys now:", list(best_models.keys()))

# Persist registry snapshot to disk (single source of truth)
with open("models/best_models_registry.json", "w", encoding="utf-8") as f:
    json.dump(best_models, f, indent=2, ensure_ascii=False)


import torch
import gc

del model_5
del trainer_5 # if using Hugging Face
gc.collect()
torch.cuda.empty_cache() 

# Now the next model can start with a fresh 8GB

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at GroNLP/bert-base-dutch-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\P70092814\AppData\Local\Temp\ipykernel_27036\135583952.py:107: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer_5 = Trainer(

✅ Saved 5way best model to: models\text_only_5way_best_20260506_122247
Registry keys now: ['text_only_5way']

In [41]:
best_models

{'text_only_5way': {'model_key': 'text_only_5way',
  'saved_path': 'models\\text_only_5way_best_20260506_120157',
  'best_checkpoint': './text_only_model_5\\checkpoint-702',
  'time_saved': '20260506_120157',
  'training_args': {'output_dir': './text_only_model_5',
   'overwrite_output_dir': False,
   'do_train': False,
   'do_eval': True,
   'do_predict': False,
   'eval_strategy': 'epoch',
   'prediction_loss_only': False,
   'per_device_train_batch_size': 16,
   'per_device_eval_batch_size': 32,
   'per_gpu_train_batch_size': None,
   'per_gpu_eval_batch_size': None,
   'gradient_accumulation_steps': 1,
   'eval_accumulation_steps': None,
   'eval_delay': 0,
   'torch_empty_cache_steps': None,
   'learning_rate': 2e-05,
   'weight_decay': 0.01,
   'adam_beta1': 0.9,
   'adam_beta2': 0.999,
   'adam_epsilon': 1e-08,
   'max_grad_norm': 1.0,
   'num_train_epochs': 4,
   'max_steps': -1,
   'lr_scheduler_type': 'linear',
   'lr_scheduler_kwargs': {},
   'warmup_ratio': 0.0,
   'warmup_steps': 0,
   'log_level': 'passive',
   'log_level_replica': 'warning',
   'log_on_each_node': True,
   'logging_dir': './text_only_model_5\\runs\\May06_11-42-32_MWP-10820534408',
   'logging_strategy': 'steps',
   'logging_first_step': False,
   'logging_steps': 50,
   'logging_nan_inf_filter': True,
   'save_strategy': 'epoch',
   'save_steps': 500,
   'save_total_limit': None,
   'save_safetensors': True,
   'save_on_each_node': False,
   'save_only_model': False,
   'restore_callback_states_from_checkpoint': False,
   'no_cuda': False,
   'use_cpu': False,
   'use_mps_device': False,
   'seed': 42,
   'data_seed': None,
   'jit_mode_eval': False,
   'use_ipex': False,
   'bf16': False,
   'fp16': False,
   'fp16_opt_level': 'O1',
   'half_precision_backend': 'auto',
   'bf16_full_eval': False,
   'fp16_full_eval': False,
   'tf32': None,
   'local_rank': 0,
   'ddp_backend': None,
   'tpu_num_cores': None,
   'tpu_metrics_debug': False,
   'debug': [],
   'dataloader_drop_last': False,
   'eval_steps': None,
   'dataloader_num_workers': 0,
   'dataloader_prefetch_factor': None,
   'past_index': -1,
   'run_name': None,
   'disable_tqdm': False,
   'remove_unused_columns': True,
   'label_names': None,
   'load_best_model_at_end': True,
   'metric_for_best_model': 'macro_f1',
   'greater_is_better': True,
   'ignore_data_skip': False,
   'fsdp': [],
   'fsdp_min_num_params': 0,
   'fsdp_config': {'min_num_params': 0,
    'xla': False,
    'xla_fsdp_v2': False,
    'xla_fsdp_grad_ckpt': False},
   'fsdp_transformer_layer_cls_to_wrap': None,
   'accelerator_config': {'split_batches': False,
    'dispatch_batches': None,
    'even_batches': True,
    'use_seedable_sampler': True,
    'non_blocking': False,
    'gradient_accumulation_kwargs': None},
   'parallelism_config': None,
   'deepspeed': None,
   'label_smoothing_factor': 0.0,
   'optim': 'adamw_torch',
   'optim_args': None,
   'adafactor': False,
   'group_by_length': False,
   'length_column_name': 'length',
   'report_to': [],
   'ddp_find_unused_parameters': None,
   'ddp_bucket_cap_mb': None,
   'ddp_broadcast_buffers': None,
   'dataloader_pin_memory': True,
   'dataloader_persistent_workers': False,
   'skip_memory_metrics': True,
   'use_legacy_prediction_loop': False,
   'push_to_hub': False,
   'resume_from_checkpoint': None,
   'hub_model_id': None,
   'hub_strategy': 'every_save',
   'hub_token': '<HUB_TOKEN>',
   'hub_private_repo': None,
   'hub_always_push': False,
   'hub_revision': None,
   'gradient_checkpointing': False,
   'gradient_checkpointing_kwargs': None,
   'include_inputs_for_metrics': False,
   'include_for_metrics': [],
   'eval_do_concat_batches': True,
   'fp16_backend': 'auto',
   'push_to_hub_model_id': None,
   'push_to_hub_organization': None,
   'push_to_hub_token': '<PUSH_TO_HUB_TOKEN>',
   'mp_parameters': '',
   'auto_find_batch_size': False,
   'full_determinism': False,
   'torchdynamo': None,
   'ray_scope': 'last',
   'ddp_timeout': 1800,
   'torch_compile': False,
   'torch_compile_backend': None,
   'torch_compile_mode': None,
   'include_tokens_per_second': False,
   'include_num_input_tokens_seen': False,
   'neftune_noise_alpha': None,
   'optim_target_modules': None,
   'batch_eval_metrics': False,
   'eval_on_start': False,
   'use_liger_kernel': False,
   'liger_kernel_config': None,
   'eval_use_gather_object': False,
   'average_tokens_across_devices': False},
  'global_step': 1404,
  'best_metric': 0.666674202701169,
  'best_model_checkpoint': './text_only_model_5\\checkpoint-702',
  'stage': 0,
  'experiment': '1',
  'variant': 'text_only',
  'task': '5_way_legal_role_classification',
  'model_name': 'GroNLP/bert-base-dutch-cased',
  'labels_order': ['None',
   'beoordeling',
   'beslissing',
   'materiele feiten',
   'proceshandelingen'],
  'text_col': 'sent_text',
  'max_len': 256,
  'train_rows': 5608,
  'eval_rows': 1281,
  'test_rows': 1502}}

## 2. Pipeline Stage 1

In [46]:

import torch
import gc

gc.collect()
torch.cuda.empty_cache()

In [47]:
# ============================================================
# STAGE 1 — TRAINING (Binary Gatekeeper: None vs Labelled)
# ================================a============================

from transformers import TrainingArguments
# ============================================================
# 3) MODEL DEFINITION & TOKENIZATION (shared preprocessing)
# ============================================================
model_name = "GroNLP/bert-base-dutch-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)

# ------------------------------------------------------------
# 1) Training configuration
# ------------------------------------------------------------
args = TrainingArguments(
    output_dir="robbert_gatekeeper",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=6,
    weight_decay=0.01,

    eval_strategy="epoch",  
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    fp16=True,  # use mixed precision if available
    report_to="none",
)

# ------------------------------------------------------------
# 2) Metrics definition
# ------------------------------------------------------------
import evaluate
import numpy as np

metric_f1 = evaluate.load("f1")
metric_pr = evaluate.load("precision")
metric_rc = evaluate.load("recall")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "f1": metric_f1.compute(predictions=preds, references=labels, average="binary")["f1"],
        "precision": metric_pr.compute(predictions=preds, references=labels, average="binary")["precision"],
        "recall": metric_rc.compute(predictions=preds, references=labels, average="binary")["recall"],
    }

# ------------------------------------------------------------
# 3) Trainer definition (uses frozen train/eval splits)
# ------------------------------------------------------------
from transformers import Trainer

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=eval_ds,     
    compute_metrics=compute_metrics,
)

# ------------------------------------------------------------
# 4) Train Stage 1 model
# ------------------------------------------------------------
trainer.train()
stage1_meta = register_best_model(
    registry=best_models,
    model_key="stage1_gatekeeper",
    trainer=trainer,
    tokenizer=tokenizer,
    extra_meta={
        "stage": 1,
        "task": "binary_labelled_vs_unlabelled",
        "labels": ["not_labelled", "labelled"],
    }
)

print("Saved + registered:", stage1_meta["saved_path"])
print("Registry keys:", list(best_models.keys()))

os.makedirs("models", exist_ok=True)

with open("models/best_models_registry.json", "w", encoding="utf-8") as f:
    json.dump(best_models, f, indent=2, ensure_ascii=False)


import torch
import gc

del model
del trainer # if using Hugging Face
gc.collect()
torch.cuda.empty_cache() 

# Now the next model can start with a fresh 8GB

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at GroNLP/bert-base-dutch-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Saved + registered: models\stage1_gatekeeper_best_20260506_140445
Registry keys: ['text_only_5way', 'stage1_gatekeeper']

## 3. Pipeline (Stage 2)
   4-way Model &
   Individual Models

In [ ]:
# ============================================================
# STAGE 2 A — TRAIN TEXT-ONLY 4-WAY CLASSIFIER (RobBERT)
# Uses frozen splits: train_legal / eval_legal / test_legal
# ============================================================

import numpy as np
import torch
from torch.utils.data import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from sklearn.metrics import f1_score, accuracy_score

# ------------------------------------------------------------
# 1) Config + label mapping (fixed order!)
# ------------------------------------------------------------
MODEL_NAME = "GroNLP/bert-base-dutch-cased"

LEGAL_LABELS = ["beoordeling", "beslissing", "materiele feiten", "proceshandelingen"]
label2id = {l: i for i, l in enumerate(LEGAL_LABELS)}
id2label = {i: l for l, i in label2id.items()}

# 2) Start from the frozen splits (from Stage 1 split)
train_df_all = train_df.copy()
eval_df_all  = eval_df.copy()
test_df_all  = test_df.copy()

train_legal = train_df_all[train_df_all["label"].isin(LEGAL_LABELS)].copy()
eval_legal  = eval_df_all[eval_df_all["label"].isin(LEGAL_LABELS)].copy()
test_legal  = test_df_all[test_df_all["label"].isin(LEGAL_LABELS)].copy()

train_legal = train_legal.copy()
eval_legal  = eval_legal.copy()
test_legal  = test_legal.copy()   # keep untouched; evaluate later

train_legal["y"] = train_legal["label"].map(label2id)
eval_legal["y"]  = eval_legal["label"].map(label2id)
test_legal["y"]  = test_legal["label"].map(label2id)

# ------------------------------------------------------------
# 3) Tokenizer
# ------------------------------------------------------------
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

# ------------------------------------------------------------
# 4) Torch Dataset wrapper (text -> tokenized tensors)
# ------------------------------------------------------------
class TextDataset(Dataset):
    def __init__(self, df, text_col="sent_text", label_col="y", tokenizer=None, max_len=256):
        self.texts = df[text_col].astype(str).tolist()
        self.labels = df[label_col].astype(int).tolist()
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        enc = self.tokenizer(
            self.texts[idx],
            truncation=True,
            padding="max_length",
            max_length=self.max_len,
            return_tensors="pt"
        )
        item = {k: v.squeeze(0) for k, v in enc.items()}
        item["labels"] = torch.tensor(self.labels[idx], dtype=torch.long)
        return item

train_ds_4 = TextDataset(train_legal, tokenizer=tokenizer, max_len=256)
eval_ds_4  = TextDataset(eval_legal,  tokenizer=tokenizer, max_len=256)
test_ds_4  = TextDataset(test_legal,  tokenizer=tokenizer, max_len=256)

# ------------------------------------------------------------
# 5) Model
# ------------------------------------------------------------
model_4 = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=len(LEGAL_LABELS),
    id2label=id2label,
    label2id=label2id
)

# ------------------------------------------------------------
# 6) Metrics (4-way)
# ------------------------------------------------------------
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "macro_f1": f1_score(labels, preds, average="macro"),
        "micro_f1": f1_score(labels, preds, average="micro"),
    }

# ------------------------------------------------------------
# 7) Training arguments
# ------------------------------------------------------------
training_args_4 = TrainingArguments(
    output_dir="./text_only_model_4",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    fp16=True,
    report_to="none"
)

# ------------------------------------------------------------
# 8) Trainer (IMPORTANT: eval_dataset = eval_ds_4, not test)
# ------------------------------------------------------------
trainer_4 = Trainer(
    model=model_4,
    args=training_args_4,
    train_dataset=train_ds_4,
    eval_dataset=eval_ds_4,          #validation split
    tokenizer=tokenizer,
    compute_metrics=compute_metrics
)

# ------------------------------------------------------------
# 9) Train Stage 2A
# ------------------------------------------------------------
trainer_4.train()

# ------------------------------------------------------------
# 10) Save best Stage 2A model into registry
# ------------------------------------------------------------

os.makedirs("models", exist_ok=True)

if "best_models" not in globals():
    best_models = {}

stage2a_meta = register_best_model(
    registry=best_models,
    model_key="stage2_text_only_4way",
    trainer=trainer_4,
    tokenizer=tokenizer,
    base_save_dir="models",
    extra_meta={
        "stage": 2,
        "experiment": "2A",
        "variant": "text_only",
        "task": "4_way_legal_role_classification",
        "model_name": MODEL_NAME,
        "labels_order": LEGAL_LABELS,
        "text_col": "sent_text",
        "max_len": 256,
        "train_rows": len(train_legal),
        "eval_rows": len(eval_legal),
        "test_rows": len(test_legal),
        
    }
)

print("✅ Saved Stage 2A best model to:", stage2a_meta["saved_path"])
print("Registry keys now:", list(best_models.keys()))

# Persist registry snapshot to disk (single source of truth)
with open("models/best_models_registry.json", "w", encoding="utf-8") as f:
    json.dump(best_models, f, indent=2, ensure_ascii=False)


import torch
import gc

gc.collect()
torch.cuda.empty_cache()

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at GroNLP/bert-base-dutch-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\P70092814\AppData\Local\Temp\ipykernel_27036\1491212871.py:115: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer_4 = Trainer(

✅ Saved Stage 2A best model to: models\stage2_text_only_4way_best_20260506_141904
Registry keys now: ['text_only_5way', 'stage1_gatekeeper', 'stage2_text_only_4way']

NameError: name 'model' is not defined

In [51]:
import torch
import gc

gc.collect()
torch.cuda.empty_cache()

In [52]:
# ============================================================
# STAGE 2 B — TRAIN 4 OVRS (One-vs-Rest) CLASSIFIERS (RobBERT)
# Uses frozen splits: train_legal / eval_legal / test_legal
# ============================================================
import numpy as np
import pandas as pd
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
from sklearn.metrics import classification_report, f1_score, accuracy_score
import evaluate

MODEL_NAME = "GroNLP/bert-base-dutch-cased"
LEGAL_LABELS = ["beoordeling", "beslissing", "materiele feiten", "proceshandelingen"]

tokenizer_ovr = AutoTokenizer.from_pretrained(MODEL_NAME)

def tok(batch):
    return tokenizer_ovr(
        batch["text"],
        truncation=True,
        padding="max_length",
        max_length=256
    )

# Make OVR dataframe
def make_ovr_df(df_legal: pd.DataFrame, pos_label: str) -> pd.DataFrame:
    """
    Option 2.1:
      - df_legal contains ONLY rows with label in LEGAL_LABELS
      - y = 1 if label == pos_label else 0
    """
    out = df_legal.copy()
    out["y"] = (out["label"] == pos_label).astype(int)
    return out

def make_hf_ds(df_bin: pd.DataFrame) -> Dataset:
    ds = Dataset.from_pandas(
        df_bin[["sent_text", "y"]].rename(columns={"sent_text": "text", "y": "labels"})
    )
    ds = ds.map(tok, batched=True)
    return ds

#Train one OVR model per label
metric_f1 = evaluate.load("f1")
metric_pr = evaluate.load("precision")
metric_rc = evaluate.load("recall")

def compute_metrics_bin(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "f1": metric_f1.compute(predictions=preds, references=labels, average="binary")["f1"],
        "precision": metric_pr.compute(predictions=preds, references=labels, average="binary")["precision"],
        "recall": metric_rc.compute(predictions=preds, references=labels, average="binary")["recall"],
    }

def train_one_ovr_model(pos_label: str, train_legal: pd.DataFrame, eval_legal: pd.DataFrame):
    # Build binary train/eval
    train_bin_df = make_ovr_df(train_legal, pos_label)
    eval_bin_df  = make_ovr_df(eval_legal, pos_label)

    train_ds = make_hf_ds(train_bin_df)
    eval_ds  = make_hf_ds(eval_bin_df)

    model = AutoModelForSequenceClassification.from_pretrained(
        MODEL_NAME,
        num_labels=2
    )

    args = TrainingArguments(
        output_dir=f"./ovr_{pos_label.replace(' ', '_')}",
        learning_rate=2e-5,
        per_device_train_batch_size=16,
        per_device_eval_batch_size=32,
        num_train_epochs=3,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="f1",
        report_to="none",
        fp16=True,
        
    )

    trainer = Trainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=eval_ds,
        compute_metrics=compute_metrics_bin,
        tokenizer=tokenizer_ovr,
    )

    trainer.train()
    return trainer


ovr_trainers = {}

ovr_trainers = {}

for lab in LEGAL_LABELS[2:]:  # just run one for demo
    gc.collect()
    torch.cuda.empty_cache() 
    print(f"\n==============================")
    print(f"Training OvR model for: {lab}")
    print(f"==============================")

    import torch

    print("CUDA available:", torch.cuda.is_available())
    print("CUDA device count:", torch.cuda.device_count())
    if torch.cuda.is_available():
        print("GPU name:", torch.cuda.get_device_name(0))
    

    tr = train_one_ovr_model(lab, train_legal, eval_legal)
    ovr_trainers[lab] = tr

    # ---- Register best model in global registry ----
    model_key = f"ovr_{lab.replace(' ', '_')}".lower()

    meta = register_best_model(
        registry=best_models,
        model_key=model_key,
        trainer=tr,
        tokenizer=tokenizer_ovr,   
        extra_meta={
            "stage": 2,
            "type": "ovr_binary",
            "pos_label": lab,
            "labels": ["not_"+lab, lab],  
        }
    )

    print("Saved:", meta["saved_path"])
    print("Best ckpt:", meta["best_checkpoint"])
    print("Registry keys:", list(best_models.keys()))

    os.makedirs("models", exist_ok=True)

    with open("models/best_models_registry.json", "w", encoding="utf-8") as f:
        json.dump(best_models, f, indent=2, ensure_ascii=False)

==============================
Training OvR model for: materiele feiten
==============================
CUDA available: True
CUDA device count: 1
GPU name: NVIDIA GeForce RTX 4060 Laptop GPU

Map:   0%|          | 0/3611 [00:00<?, ? examples/s]

Map:   0%|          | 0/759 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at GroNLP/bert-base-dutch-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\P70092814\AppData\Local\Temp\ipykernel_27036\3721775749.py:92: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Saved: models\ovr_materiele_feiten_best_20260506_152348
Best ckpt: ./ovr_materiele_feiten\checkpoint-678
Registry keys: ['text_only_5way', 'stage1_gatekeeper', 'stage2_text_only_4way', 'ovr_beoordeling', 'ovr_beslissing', 'ovr_materiele_feiten']

==============================
Training OvR model for: proceshandelingen
==============================
CUDA available: True
CUDA device count: 1
GPU name: NVIDIA GeForce RTX 4060 Laptop GPU

Map:   0%|          | 0/3611 [00:00<?, ? examples/s]

Map:   0%|          | 0/759 [00:00<?, ? examples/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at GroNLP/bert-base-dutch-cased and are newly initialized: ['bert.pooler.dense.bias', 'bert.pooler.dense.weight', 'classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\P70092814\AppData\Local\Temp\ipykernel_27036\3721775749.py:92: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Saved: models\ovr_proceshandelingen_best_20260506_160617
Best ckpt: ./ovr_proceshandelingen\checkpoint-678
Registry keys: ['text_only_5way', 'stage1_gatekeeper', 'stage2_text_only_4way', 'ovr_beoordeling', 'ovr_beslissing', 'ovr_materiele_feiten', 'ovr_proceshandelingen']